%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'DGE_CRED_Model';
M_.dynare_version = '5.3';
oo_.dynare_version = '5.3';
options_.dynare_version = '5.3';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(61,1);
M_.exo_names_tex = cell(61,1);
M_.exo_names_long = cell(61,1);
M_.exo_names(1) = {'exo_tauC'};
M_.exo_names_tex(1) = {'{\eta_{\tau^C}}'};
M_.exo_names_long(1) = {'exogeneous consumption tax'};
M_.exo_names(2) = {'exo_tauH'};
M_.exo_names_tex(2) = {'{\eta_{\tau^C}}'};
M_.exo_names_long(2) = {'exogeneous housing tax'};
M_.exo_names(3) = {'exo_tauNH'};
M_.exo_names_tex(3) = {'{\eta_{\tau^{N,H}}}'};
M_.exo_names_long(3) = {'exogeneous labour income tax paid by households'};
M_.exo_names(4) = {'exo_tauKH'};
M_.exo_names_tex(4) = {'{\eta_{\tau^{K,H}}}'};
M_.exo_names_long(4) = {'exogeneous capital income tax paid by households'};
M_.exo_names(5) = {'exo_H'};
M_.exo_names_tex(5) = {'{\eta_{H}}'};
M_.exo_names_long(5) = {'exogeneous housing area to population ratio'};
M_.exo_names(6) = {'exo_DH'};
M_.exo_names_tex(6) = {'{\eta_{D^{H}}}'};
M_.exo_names_long(6) = {'exogeneous damage to housing stock'};
M_.exo_names(7) = {'exo_PoP'};
M_.exo_names_tex(7) = {'{\eta_{PoP}}'};
M_.exo_names_long(7) = {'exogeneous population'};
M_.exo_names(8) = {'exo_BG'};
M_.exo_names_tex(8) = {'{\eta_{BG}}'};
M_.exo_names_long(8) = {'exogenous structural balance'};
M_.exo_names(9) = {'exo_rf'};
M_.exo_names_tex(9) = {'{\eta_{r^f}}'};
M_.exo_names_long(9) = {'exogenous world interest rate'};
M_.exo_names(10) = {'exo_P'};
M_.exo_names_tex(10) = {'{\eta_{P}}'};
M_.exo_names_long(10) = {'exogenous price level'};
M_.exo_names(11) = {'exo_M'};
M_.exo_names_tex(11) = {'{\eta_{M}}'};
M_.exo_names_long(11) = {'exogenous import shock'};
M_.exo_names(12) = {'exo_X_1'};
M_.exo_names_tex(12) = {'{\eta_{X,s}}'};
M_.exo_names_long(12) = {'exogenus demand for subsector exports'};
M_.exo_names(13) = {'exo_1_1'};
M_.exo_names_tex(13) = {'{\eta_{A,s,r}}'};
M_.exo_names_long(13) = {'exogenus TFP'};
M_.exo_names(14) = {'exo_N_1_1'};
M_.exo_names_tex(14) = {'{\eta_{A^{N},s,r}}'};
M_.exo_names_long(14) = {'exogenous labour specific TFP'};
M_.exo_names(15) = {'exo_K_1_1'};
M_.exo_names_tex(15) = {'{\eta_{A^{K},s,r}}'};
M_.exo_names_long(15) = {'exogenous capital specific TFP'};
M_.exo_names(16) = {'exo_D_1_1'};
M_.exo_names_tex(16) = {'{\eta_{D,s,r}}'};
M_.exo_names_long(16) = {'exogenus damage induced by climate change for the subsector'};
M_.exo_names(17) = {'exo_D_N_1_1'};
M_.exo_names_tex(17) = {'{\eta_{D^{N},s,r}}'};
M_.exo_names_long(17) = {'exogenus damage induced by climate change for labour productivity in the subsector'};
M_.exo_names(18) = {'exo_D_K_1_1'};
M_.exo_names_tex(18) = {'{\eta_{D^{K},s,r}}'};
M_.exo_names_long(18) = {'exogenus damage induced by climate change for capital productivity in the subsector'};
M_.exo_names(19) = {'exo_tauKF_1_1'};
M_.exo_names_tex(19) = {'{\eta_{\tau^{K},s,r}}'};
M_.exo_names_long(19) = {'exogenous sector and region corporate tax rate'};
M_.exo_names(20) = {'exo_tauNF_1_1'};
M_.exo_names_tex(20) = {'{\eta_{\tau^{N},s,r}}'};
M_.exo_names_long(20) = {'exogenous sector and region labour tax rate'};
M_.exo_names(21) = {'exo_GA_1_1'};
M_.exo_names_tex(21) = {'{\eta_{G^{A},s,r}}'};
M_.exo_names_long(21) = {'exogenous sector adaptation expenditure against landslide'};
M_.exo_names(22) = {'exo_IAP_1_1'};
M_.exo_names_tex(22) = {'{\eta_{I^{A,P},s,r}}'};
M_.exo_names_long(22) = {'exogenous sector private adaptation expenditure against landslide'};
M_.exo_names(23) = {'exo_X_2'};
M_.exo_names_tex(23) = {'{\eta_{X,s}}'};
M_.exo_names_long(23) = {'exogenus demand for subsector exports'};
M_.exo_names(24) = {'exo_M_2'};
M_.exo_names_tex(24) = {'{\eta_{M,s}}'};
M_.exo_names_long(24) = {'exogenus price development of sector imports'};
M_.exo_names(25) = {'exo_2_1'};
M_.exo_names_tex(25) = {'{\eta_{A,s,r}}'};
M_.exo_names_long(25) = {'exogenus TFP'};
M_.exo_names(26) = {'exo_N_2_1'};
M_.exo_names_tex(26) = {'{\eta_{A^{N},s,r}}'};
M_.exo_names_long(26) = {'exogenous labour specific TFP'};
M_.exo_names(27) = {'exo_K_2_1'};
M_.exo_names_tex(27) = {'{\eta_{A^{K},s,r}}'};
M_.exo_names_long(27) = {'exogenous capital specific TFP'};
M_.exo_names(28) = {'exo_D_2_1'};
M_.exo_names_tex(28) = {'{\eta_{D,s,r}}'};
M_.exo_names_long(28) = {'exogenus damage induced by climate change for the subsector'};
M_.exo_names(29) = {'exo_D_N_2_1'};
M_.exo_names_tex(29) = {'{\eta_{D^{N},s,r}}'};
M_.exo_names_long(29) = {'exogenus damage induced by climate change for labour productivity in the subsector'};
M_.exo_names(30) = {'exo_D_K_2_1'};
M_.exo_names_tex(30) = {'{\eta_{D^{K},s,r}}'};
M_.exo_names_long(30) = {'exogenus damage induced by climate change for capital productivity in the subsector'};
M_.exo_names(31) = {'exo_tauKF_2_1'};
M_.exo_names_tex(31) = {'{\eta_{\tau^{K},s,r}}'};
M_.exo_names_long(31) = {'exogenous sector and region corporate tax rate'};
M_.exo_names(32) = {'exo_tauNF_2_1'};
M_.exo_names_tex(32) = {'{\eta_{\tau^{N},s,r}}'};
M_.exo_names_long(32) = {'exogenous sector and region labour tax rate'};
M_.exo_names(33) = {'exo_GA_2_1'};
M_.exo_names_tex(33) = {'{\eta_{G^{A},s,r}}'};
M_.exo_names_long(33) = {'exogenous sector adaptation expenditure against landslide'};
M_.exo_names(34) = {'exo_IAP_2_1'};
M_.exo_names_tex(34) = {'{\eta_{I^{A,P},s,r}}'};
M_.exo_names_long(34) = {'exogenous sector private adaptation expenditure against landslide'};
M_.exo_names(35) = {'exo_X_3'};
M_.exo_names_tex(35) = {'{\eta_{X,s}}'};
M_.exo_names_long(35) = {'exogenus demand for subsector exports'};
M_.exo_names(36) = {'exo_M_3'};
M_.exo_names_tex(36) = {'{\eta_{M,s}}'};
M_.exo_names_long(36) = {'exogenus price development of sector imports'};
M_.exo_names(37) = {'exo_3_1'};
M_.exo_names_tex(37) = {'{\eta_{A,s,r}}'};
M_.exo_names_long(37) = {'exogenus TFP'};
M_.exo_names(38) = {'exo_N_3_1'};
M_.exo_names_tex(38) = {'{\eta_{A^{N},s,r}}'};
M_.exo_names_long(38) = {'exogenous labour specific TFP'};
M_.exo_names(39) = {'exo_K_3_1'};
M_.exo_names_tex(39) = {'{\eta_{A^{K},s,r}}'};
M_.exo_names_long(39) = {'exogenous capital specific TFP'};
M_.exo_names(40) = {'exo_D_3_1'};
M_.exo_names_tex(40) = {'{\eta_{D,s,r}}'};
M_.exo_names_long(40) = {'exogenus damage induced by climate change for the subsector'};
M_.exo_names(41) = {'exo_D_N_3_1'};
M_.exo_names_tex(41) = {'{\eta_{D^{N},s,r}}'};
M_.exo_names_long(41) = {'exogenus damage induced by climate change for labour productivity in the subsector'};
M_.exo_names(42) = {'exo_D_K_3_1'};
M_.exo_names_tex(42) = {'{\eta_{D^{K},s,r}}'};
M_.exo_names_long(42) = {'exogenus damage induced by climate change for capital productivity in the subsector'};
M_.exo_names(43) = {'exo_tauKF_3_1'};
M_.exo_names_tex(43) = {'{\eta_{\tau^{K},s,r}}'};
M_.exo_names_long(43) = {'exogenous sector and region corporate tax rate'};
M_.exo_names(44) = {'exo_tauNF_3_1'};
M_.exo_names_tex(44) = {'{\eta_{\tau^{N},s,r}}'};
M_.exo_names_long(44) = {'exogenous sector and region labour tax rate'};
M_.exo_names(45) = {'exo_GA_3_1'};
M_.exo_names_tex(45) = {'{\eta_{G^{A},s,r}}'};
M_.exo_names_long(45) = {'exogenous sector adaptation expenditure against landslide'};
M_.exo_names(46) = {'exo_IAP_3_1'};
M_.exo_names_tex(46) = {'{\eta_{I^{A,P},s,r}}'};
M_.exo_names_long(46) = {'exogenous sector private adaptation expenditure against landslide'};
M_.exo_names(47) = {'exo_G_A_DH'};
M_.exo_names_tex(47) = {'{\eta_{G^{A,H}}}'};
M_.exo_names_long(47) = {'exogenous sector adaptation expenditure for housing'};
M_.exo_names(48) = {'exo_I_AP_DH'};
M_.exo_names_tex(48) = {'{\eta_{G^{A,P,H}}}'};
M_.exo_names_long(48) = {'exogenous sector private adaptation expenditure for housing'};
M_.exo_names(49) = {'exo_SL'};
M_.exo_names_tex(49) = {'{\eta_{SL,r}}'};
M_.exo_names_long(49) = {'exogenus SL'};
M_.exo_names(50) = {'exo_tas_1'};
M_.exo_names_tex(50) = {'{\eta_{tas,r}}'};
M_.exo_names_long(50) = {'exogenus regional tas'};
M_.exo_names(51) = {'exo_SfcWind_1'};
M_.exo_names_tex(51) = {'{\eta_{SfcWind,r}}'};
M_.exo_names_long(51) = {'exogenus regional SfcWind'};
M_.exo_names(52) = {'exo_pr_1'};
M_.exo_names_tex(52) = {'{\eta_{pr,r}}'};
M_.exo_names_long(52) = {'exogenus regional pr'};
M_.exo_names(53) = {'exo_sunshine_1'};
M_.exo_names_tex(53) = {'{\eta_{sunshine,r}}'};
M_.exo_names_long(53) = {'exogenus regional sunshine'};
M_.exo_names(54) = {'exo_hurs_1'};
M_.exo_names_tex(54) = {'{\eta_{hurs,r}}'};
M_.exo_names_long(54) = {'exogenus regional hurs'};
M_.exo_names(55) = {'exo_heatwave_1'};
M_.exo_names_tex(55) = {'{\eta_{heatwave,r}}'};
M_.exo_names_long(55) = {'exogenus regional heatwave'};
M_.exo_names(56) = {'exo_maxdrydays_1'};
M_.exo_names_tex(56) = {'{\eta_{maxdrydays,r}}'};
M_.exo_names_long(56) = {'exogenus regional maxdrydays'};
M_.exo_names(57) = {'exo_maxwetdays_1'};
M_.exo_names_tex(57) = {'{\eta_{maxwetdays,r}}'};
M_.exo_names_long(57) = {'exogenus regional maxwetdays'};
M_.exo_names(58) = {'exo_storms_1'};
M_.exo_names_tex(58) = {'{\eta_{storms,r}}'};
M_.exo_names_long(58) = {'exogenus regional storms'};
M_.exo_names(59) = {'exo_floods_1'};
M_.exo_names_tex(59) = {'{\eta_{floods,r}}'};
M_.exo_names_long(59) = {'exogenus regional floods'};
M_.exo_names(60) = {'exo_fire_1'};
M_.exo_names_tex(60) = {'{\eta_{fire,r}}'};
M_.exo_names_long(60) = {'exogenus regional fire'};
M_.exo_names(61) = {'exo_landslide_1'};
M_.exo_names_tex(61) = {'{\eta_{landslide,r}}'};
M_.exo_names_long(61) = {'exogenus regional landslide'};
M_.endo_names = cell(163,1);
M_.endo_names_tex = cell(163,1);
M_.endo_names_long = cell(163,1);
M_.endo_names(1) = {'K'};
M_.endo_names_tex(1) = {'K'};
M_.endo_names_long(1) = {'capital stock'};
M_.endo_names(2) = {'N'};
M_.endo_names_tex(2) = {'N'};
M_.endo_names_long(2) = {'labour'};
M_.endo_names(3) = {'SL'};
M_.endo_names_tex(3) = {'{SL}'};
M_.endo_names_long(3) = {'SL'};
M_.endo_names(4) = {'tas_1'};
M_.endo_names_tex(4) = {'{tas_{r}}'};
M_.endo_names_long(4) = {'tas'};
M_.endo_names(5) = {'SfcWind_1'};
M_.endo_names_tex(5) = {'{SfcWind_{r}}'};
M_.endo_names_long(5) = {'SfcWind'};
M_.endo_names(6) = {'pr_1'};
M_.endo_names_tex(6) = {'{pr_{r}}'};
M_.endo_names_long(6) = {'pr'};
M_.endo_names(7) = {'sunshine_1'};
M_.endo_names_tex(7) = {'{sunshine_{r}}'};
M_.endo_names_long(7) = {'sunshine'};
M_.endo_names(8) = {'hurs_1'};
M_.endo_names_tex(8) = {'{hurs_{r}}'};
M_.endo_names_long(8) = {'hurs'};
M_.endo_names(9) = {'heatwave_1'};
M_.endo_names_tex(9) = {'{heatwave_{r}}'};
M_.endo_names_long(9) = {'heatwave'};
M_.endo_names(10) = {'maxdrydays_1'};
M_.endo_names_tex(10) = {'{maxdrydays_{r}}'};
M_.endo_names_long(10) = {'maxdrydays'};
M_.endo_names(11) = {'maxwetdays_1'};
M_.endo_names_tex(11) = {'{maxwetdays_{r}}'};
M_.endo_names_long(11) = {'maxwetdays'};
M_.endo_names(12) = {'storms_1'};
M_.endo_names_tex(12) = {'{storms_{r}}'};
M_.endo_names_long(12) = {'storms'};
M_.endo_names(13) = {'floods_1'};
M_.endo_names_tex(13) = {'{floods_{r}}'};
M_.endo_names_long(13) = {'floods'};
M_.endo_names(14) = {'fire_1'};
M_.endo_names_tex(14) = {'{fire_{r}}'};
M_.endo_names_long(14) = {'fire'};
M_.endo_names(15) = {'landslide_1'};
M_.endo_names_tex(15) = {'{landslide_{r}}'};
M_.endo_names_long(15) = {'landslide'};
M_.endo_names(16) = {'I_1'};
M_.endo_names_tex(16) = {'{I_k}'};
M_.endo_names_long(16) = {'sector private investment'};
M_.endo_names(17) = {'Y_1'};
M_.endo_names_tex(17) = {'{Y_s}'};
M_.endo_names_long(17) = {'sector GDP'};
M_.endo_names(18) = {'Q_D_1'};
M_.endo_names_tex(18) = {'{Q^{D}_s}'};
M_.endo_names_long(18) = {'domesitcally used sector output'};
M_.endo_names(19) = {'Q_I_1'};
M_.endo_names_tex(19) = {'{Q^{I}_s}'};
M_.endo_names_long(19) = {'sector intermediate inputs'};
M_.endo_names(20) = {'M_1'};
M_.endo_names_tex(20) = {'{M_s}'};
M_.endo_names_long(20) = {'sector imports'};
M_.endo_names(21) = {'X_1'};
M_.endo_names_tex(21) = {'{X_s}'};
M_.endo_names_long(21) = {'sector exports'};
M_.endo_names(22) = {'D_X_1'};
M_.endo_names_tex(22) = {'{D^{X}_s}'};
M_.endo_names_long(22) = {'world demand for sector exports'};
M_.endo_names(23) = {'K_1'};
M_.endo_names_tex(23) = {'{K_s}'};
M_.endo_names_long(23) = {'sector capital'};
M_.endo_names(24) = {'N_1'};
M_.endo_names_tex(24) = {'{N_s}'};
M_.endo_names_long(24) = {'sector employment'};
M_.endo_names(25) = {'P_D_1'};
M_.endo_names_tex(25) = {'{P^{D}_s}'};
M_.endo_names_long(25) = {'domestic sector price index'};
M_.endo_names(26) = {'P_M_1'};
M_.endo_names_tex(26) = {'{P^{M}_s}'};
M_.endo_names_long(26) = {'imports sector price index'};
M_.endo_names(27) = {'W_1'};
M_.endo_names_tex(27) = {'{W_s}'};
M_.endo_names_long(27) = {'sector wage index'};
M_.endo_names(28) = {'Q_1_1'};
M_.endo_names_tex(28) = {'{Q_{s,r}}'};
M_.endo_names_long(28) = {'regional sector Output'};
M_.endo_names(29) = {'W_1_1'};
M_.endo_names_tex(29) = {'{W_{s,r}}'};
M_.endo_names_long(29) = {'regional wage rate for sector labour'};
M_.endo_names(30) = {'tauKF_1_1'};
M_.endo_names_tex(30) = {'{\tau^{K}_{s,r}}'};
M_.endo_names_long(30) = {'regional sector corporate tax rate on capital'};
M_.endo_names(31) = {'tauNF_1_1'};
M_.endo_names_tex(31) = {'{\tau^{N}_{s,r}}'};
M_.endo_names_long(31) = {'regional sector labour tax rate on capital'};
M_.endo_names(32) = {'P_D_1_1'};
M_.endo_names_tex(32) = {'{P^D_{s,r}}'};
M_.endo_names_long(32) = {'regional sector price index'};
M_.endo_names(33) = {'I_2'};
M_.endo_names_tex(33) = {'{I_k}'};
M_.endo_names_long(33) = {'sector private investment'};
M_.endo_names(34) = {'Y_2'};
M_.endo_names_tex(34) = {'{Y_s}'};
M_.endo_names_long(34) = {'sector GDP'};
M_.endo_names(35) = {'Q_D_2'};
M_.endo_names_tex(35) = {'{Q^{D}_s}'};
M_.endo_names_long(35) = {'domesitcally used sector output'};
M_.endo_names(36) = {'Q_I_2'};
M_.endo_names_tex(36) = {'{Q^{I}_s}'};
M_.endo_names_long(36) = {'sector intermediate inputs'};
M_.endo_names(37) = {'M_2'};
M_.endo_names_tex(37) = {'{M_s}'};
M_.endo_names_long(37) = {'sector imports'};
M_.endo_names(38) = {'X_2'};
M_.endo_names_tex(38) = {'{X_s}'};
M_.endo_names_long(38) = {'sector exports'};
M_.endo_names(39) = {'D_X_2'};
M_.endo_names_tex(39) = {'{D^{X}_s}'};
M_.endo_names_long(39) = {'world demand for sector exports'};
M_.endo_names(40) = {'K_2'};
M_.endo_names_tex(40) = {'{K_s}'};
M_.endo_names_long(40) = {'sector capital'};
M_.endo_names(41) = {'N_2'};
M_.endo_names_tex(41) = {'{N_s}'};
M_.endo_names_long(41) = {'sector employment'};
M_.endo_names(42) = {'P_D_2'};
M_.endo_names_tex(42) = {'{P^{D}_s}'};
M_.endo_names_long(42) = {'domestic sector price index'};
M_.endo_names(43) = {'P_M_2'};
M_.endo_names_tex(43) = {'{P^{M}_s}'};
M_.endo_names_long(43) = {'imports sector price index'};
M_.endo_names(44) = {'W_2'};
M_.endo_names_tex(44) = {'{W_s}'};
M_.endo_names_long(44) = {'sector wage index'};
M_.endo_names(45) = {'Q_2_1'};
M_.endo_names_tex(45) = {'{Q_{s,r}}'};
M_.endo_names_long(45) = {'regional sector Output'};
M_.endo_names(46) = {'W_2_1'};
M_.endo_names_tex(46) = {'{W_{s,r}}'};
M_.endo_names_long(46) = {'regional wage rate for sector labour'};
M_.endo_names(47) = {'tauKF_2_1'};
M_.endo_names_tex(47) = {'{\tau^{K}_{s,r}}'};
M_.endo_names_long(47) = {'regional sector corporate tax rate on capital'};
M_.endo_names(48) = {'tauNF_2_1'};
M_.endo_names_tex(48) = {'{\tau^{N}_{s,r}}'};
M_.endo_names_long(48) = {'regional sector labour tax rate on capital'};
M_.endo_names(49) = {'P_D_2_1'};
M_.endo_names_tex(49) = {'{P^D_{s,r}}'};
M_.endo_names_long(49) = {'regional sector price index'};
M_.endo_names(50) = {'I_3'};
M_.endo_names_tex(50) = {'{I_k}'};
M_.endo_names_long(50) = {'sector private investment'};
M_.endo_names(51) = {'Y_3'};
M_.endo_names_tex(51) = {'{Y_s}'};
M_.endo_names_long(51) = {'sector GDP'};
M_.endo_names(52) = {'Q_D_3'};
M_.endo_names_tex(52) = {'{Q^{D}_s}'};
M_.endo_names_long(52) = {'domesitcally used sector output'};
M_.endo_names(53) = {'Q_I_3'};
M_.endo_names_tex(53) = {'{Q^{I}_s}'};
M_.endo_names_long(53) = {'sector intermediate inputs'};
M_.endo_names(54) = {'M_3'};
M_.endo_names_tex(54) = {'{M_s}'};
M_.endo_names_long(54) = {'sector imports'};
M_.endo_names(55) = {'X_3'};
M_.endo_names_tex(55) = {'{X_s}'};
M_.endo_names_long(55) = {'sector exports'};
M_.endo_names(56) = {'D_X_3'};
M_.endo_names_tex(56) = {'{D^{X}_s}'};
M_.endo_names_long(56) = {'world demand for sector exports'};
M_.endo_names(57) = {'K_3'};
M_.endo_names_tex(57) = {'{K_s}'};
M_.endo_names_long(57) = {'sector capital'};
M_.endo_names(58) = {'N_3'};
M_.endo_names_tex(58) = {'{N_s}'};
M_.endo_names_long(58) = {'sector employment'};
M_.endo_names(59) = {'P_D_3'};
M_.endo_names_tex(59) = {'{P^{D}_s}'};
M_.endo_names_long(59) = {'domestic sector price index'};
M_.endo_names(60) = {'P_M_3'};
M_.endo_names_tex(60) = {'{P^{M}_s}'};
M_.endo_names_long(60) = {'imports sector price index'};
M_.endo_names(61) = {'W_3'};
M_.endo_names_tex(61) = {'{W_s}'};
M_.endo_names_long(61) = {'sector wage index'};
M_.endo_names(62) = {'Q_3_1'};
M_.endo_names_tex(62) = {'{Q_{s,r}}'};
M_.endo_names_long(62) = {'regional sector Output'};
M_.endo_names(63) = {'W_3_1'};
M_.endo_names_tex(63) = {'{W_{s,r}}'};
M_.endo_names_long(63) = {'regional wage rate for sector labour'};
M_.endo_names(64) = {'tauKF_3_1'};
M_.endo_names_tex(64) = {'{\tau^{K}_{s,r}}'};
M_.endo_names_long(64) = {'regional sector corporate tax rate on capital'};
M_.endo_names(65) = {'tauNF_3_1'};
M_.endo_names_tex(65) = {'{\tau^{N}_{s,r}}'};
M_.endo_names_long(65) = {'regional sector labour tax rate on capital'};
M_.endo_names(66) = {'P_D_3_1'};
M_.endo_names_tex(66) = {'{P^D_{s,r}}'};
M_.endo_names_long(66) = {'regional sector price index'};
M_.endo_names(67) = {'P'};
M_.endo_names_tex(67) = {'P'};
M_.endo_names_long(67) = {'price level'};
M_.endo_names(68) = {'lambda'};
M_.endo_names_tex(68) = {'\lambda'};
M_.endo_names_long(68) = {'budget constraint lagrange multiplier'};
M_.endo_names(69) = {'P_D'};
M_.endo_names_tex(69) = {'{P^{D}}'};
M_.endo_names_long(69) = {'domestic price level'};
M_.endo_names(70) = {'P_M'};
M_.endo_names_tex(70) = {'{P^{M}}'};
M_.endo_names_long(70) = {'foreign  price level'};
M_.endo_names(71) = {'C'};
M_.endo_names_tex(71) = {'C'};
M_.endo_names_long(71) = {'consumption'};
M_.endo_names(72) = {'H'};
M_.endo_names_tex(72) = {'H'};
M_.endo_names_long(72) = {'houses'};
M_.endo_names(73) = {'IH'};
M_.endo_names_tex(73) = {'I^H'};
M_.endo_names_long(73) = {'investment in houses'};
M_.endo_names(74) = {'PH'};
M_.endo_names_tex(74) = {'P^H'};
M_.endo_names_long(74) = {'prices for houses'};
M_.endo_names(75) = {'DH'};
M_.endo_names_tex(75) = {'D^H'};
M_.endo_names_long(75) = {'damages to the housing stock'};
M_.endo_names(76) = {'omegaH'};
M_.endo_names_tex(76) = {'\omega^H'};
M_.endo_names_long(76) = {'lagrnage multiplier for the law of motion of houses'};
M_.endo_names(77) = {'PoP'};
M_.endo_names_tex(77) = {'PoP'};
M_.endo_names_long(77) = {'population'};
M_.endo_names(78) = {'B'};
M_.endo_names_tex(78) = {'B'};
M_.endo_names_long(78) = {'international traded bonds'};
M_.endo_names(79) = {'BG'};
M_.endo_names_tex(79) = {'BG'};
M_.endo_names_long(79) = {'government debt'};
M_.endo_names(80) = {'NX'};
M_.endo_names_tex(80) = {'NX'};
M_.endo_names_long(80) = {'net exports'};
M_.endo_names(81) = {'rf'};
M_.endo_names_tex(81) = {'{r^{f}}'};
M_.endo_names_long(81) = {'foreign interest rate'};
M_.endo_names(82) = {'G'};
M_.endo_names_tex(82) = {'G'};
M_.endo_names_long(82) = {'government expenditure'};
M_.endo_names(83) = {'tauC'};
M_.endo_names_tex(83) = {'{\tau^{C}}'};
M_.endo_names_long(83) = {'consumption tax'};
M_.endo_names(84) = {'tauH'};
M_.endo_names_tex(84) = {'{\tau^{H}}'};
M_.endo_names_long(84) = {'tax on housing'};
M_.endo_names(85) = {'tauNH'};
M_.endo_names_tex(85) = {'{\tau^{N,H}}'};
M_.endo_names_long(85) = {'labour tax'};
M_.endo_names(86) = {'tauKH'};
M_.endo_names_tex(86) = {'{\tau^{K,H}}'};
M_.endo_names_long(86) = {'capital tax'};
M_.endo_names(87) = {'KG'};
M_.endo_names_tex(87) = {'K^G'};
M_.endo_names_long(87) = {'public good capital stock'};
M_.endo_names(88) = {'I'};
M_.endo_names_tex(88) = {'I'};
M_.endo_names_long(88) = {'private investment'};
M_.endo_names(89) = {'Y'};
M_.endo_names_tex(89) = {'Y'};
M_.endo_names_long(89) = {'GDP'};
M_.endo_names(90) = {'Q_U'};
M_.endo_names_tex(90) = {'Q^{U}'};
M_.endo_names_long(90) = {'domestic used output'};
M_.endo_names(91) = {'Q_D'};
M_.endo_names_tex(91) = {'Q^{D}'};
M_.endo_names_long(91) = {'domestic produced and used products'};
M_.endo_names(92) = {'Q_I'};
M_.endo_names_tex(92) = {'Q^{I}'};
M_.endo_names_long(92) = {'demand for intermediate products'};
M_.endo_names(93) = {'Q'};
M_.endo_names_tex(93) = {'Q'};
M_.endo_names_long(93) = {'total production'};
M_.endo_names(94) = {'M'};
M_.endo_names_tex(94) = {'M'};
M_.endo_names_long(94) = {'Imports'};
M_.endo_names(95) = {'X'};
M_.endo_names_tex(95) = {'X'};
M_.endo_names_long(95) = {'Exports'};
M_.endo_names(96) = {'G_A_DH'};
M_.endo_names_tex(96) = {'{G^{A,D^H}}'};
M_.endo_names_long(96) = {'adaptation government expenditure for housing'};
M_.endo_names(97) = {'I_AP_DH'};
M_.endo_names_tex(97) = {'{I^{A,D^H}}'};
M_.endo_names_long(97) = {'adaptation private expenditure for housing'};
M_.endo_names(98) = {'Q_A_1'};
M_.endo_names_tex(98) = {'{Q^A_k}'};
M_.endo_names_long(98) = {'sector aggregate output'};
M_.endo_names(99) = {'P_A_1'};
M_.endo_names_tex(99) = {'{P^A_k}'};
M_.endo_names_long(99) = {'sector aggregate price level'};
M_.endo_names(100) = {'KH_1_1'};
M_.endo_names_tex(100) = {'{K_{k,r}}'};
M_.endo_names_long(100) = {'regional sector capital'};
M_.endo_names(101) = {'r_1_1'};
M_.endo_names_tex(101) = {'{r_{k,r}}'};
M_.endo_names_long(101) = {'regional rentqal rate for sector capital'};
M_.endo_names(102) = {'I_1_1'};
M_.endo_names_tex(102) = {'{I_{k,r}}'};
M_.endo_names_long(102) = {'regional sector investment'};
M_.endo_names(103) = {'omegaI_1_1'};
M_.endo_names_tex(103) = {'{\omega^I_{k,r}}'};
M_.endo_names_long(103) = {'shadow value of regional private sector investment'};
M_.endo_names(104) = {'Q_1'};
M_.endo_names_tex(104) = {'{Q_s}'};
M_.endo_names_long(104) = {'sector output'};
M_.endo_names(105) = {'D_1_1'};
M_.endo_names_tex(105) = {'{D_{s,r}}'};
M_.endo_names_long(105) = {'regional subsector damages'};
M_.endo_names(106) = {'D_N_1_1'};
M_.endo_names_tex(106) = {'{D^N_{s,r}}'};
M_.endo_names_long(106) = {'regional subsector damages to labour productivity'};
M_.endo_names(107) = {'D_K_1_1'};
M_.endo_names_tex(107) = {'{D^K_{s,r}}'};
M_.endo_names_long(107) = {'regional subsector destuction of capital stock'};
M_.endo_names(108) = {'K_1_1'};
M_.endo_names_tex(108) = {'{K_{s,r}}'};
M_.endo_names_long(108) = {'regional subsector capital'};
M_.endo_names(109) = {'I_AP_1_1'};
M_.endo_names_tex(109) = {'{I^{A,P}_{s,r}}'};
M_.endo_names_long(109) = {'regional subsector private adaptation government expenditure'};
M_.endo_names(110) = {'K_AP_1_1'};
M_.endo_names_tex(110) = {'{K^{A,P}_{s,r}}'};
M_.endo_names_long(110) = {'regional subsector private adaptation capital stock'};
M_.endo_names(111) = {'G_A_1_1'};
M_.endo_names_tex(111) = {'{G^{A}_{s,r}}'};
M_.endo_names_long(111) = {'regional subsector adaptation government expenditure'};
M_.endo_names(112) = {'K_A_1_1'};
M_.endo_names_tex(112) = {'{K^{A}_{s,r}}'};
M_.endo_names_long(112) = {'regional subsector adaptation capital stock'};
M_.endo_names(113) = {'P_1_1'};
M_.endo_names_tex(113) = {'{P_{s,r}}'};
M_.endo_names_long(113) = {'regional subsector price index'};
M_.endo_names(114) = {'Y_1_1'};
M_.endo_names_tex(114) = {'{Y_{s,r}}'};
M_.endo_names_long(114) = {'regional subsector GDP'};
M_.endo_names(115) = {'N_1_1'};
M_.endo_names_tex(115) = {'{N_{s,r}}'};
M_.endo_names_long(115) = {'regional subsector employment'};
M_.endo_names(116) = {'Q_I_1_1'};
M_.endo_names_tex(116) = {'{Q^{I}_{s,r}}'};
M_.endo_names_long(116) = {'regional subsector intermediate inputs'};
M_.endo_names(117) = {'A_1_1'};
M_.endo_names_tex(117) = {'{A_{s,r}}'};
M_.endo_names_long(117) = {'regional subsector TFP'};
M_.endo_names(118) = {'A_N_1_1'};
M_.endo_names_tex(118) = {'{A^{N}_{s,r}}'};
M_.endo_names_long(118) = {'regional subsector labour specific TFP'};
M_.endo_names(119) = {'A_K_1_1'};
M_.endo_names_tex(119) = {'{A^{K}_{s,r}}'};
M_.endo_names_long(119) = {'regional subsector capital specific TFP'};
M_.endo_names(120) = {'Q_A_2'};
M_.endo_names_tex(120) = {'{Q^A_k}'};
M_.endo_names_long(120) = {'sector aggregate output'};
M_.endo_names(121) = {'P_A_2'};
M_.endo_names_tex(121) = {'{P^A_k}'};
M_.endo_names_long(121) = {'sector aggregate price level'};
M_.endo_names(122) = {'KH_2_1'};
M_.endo_names_tex(122) = {'{K_{k,r}}'};
M_.endo_names_long(122) = {'regional sector capital'};
M_.endo_names(123) = {'r_2_1'};
M_.endo_names_tex(123) = {'{r_{k,r}}'};
M_.endo_names_long(123) = {'regional rentqal rate for sector capital'};
M_.endo_names(124) = {'I_2_1'};
M_.endo_names_tex(124) = {'{I_{k,r}}'};
M_.endo_names_long(124) = {'regional sector investment'};
M_.endo_names(125) = {'omegaI_2_1'};
M_.endo_names_tex(125) = {'{\omega^I_{k,r}}'};
M_.endo_names_long(125) = {'shadow value of regional private sector investment'};
M_.endo_names(126) = {'Q_2'};
M_.endo_names_tex(126) = {'{Q_s}'};
M_.endo_names_long(126) = {'sector output'};
M_.endo_names(127) = {'D_2_1'};
M_.endo_names_tex(127) = {'{D_{s,r}}'};
M_.endo_names_long(127) = {'regional subsector damages'};
M_.endo_names(128) = {'D_N_2_1'};
M_.endo_names_tex(128) = {'{D^N_{s,r}}'};
M_.endo_names_long(128) = {'regional subsector damages to labour productivity'};
M_.endo_names(129) = {'D_K_2_1'};
M_.endo_names_tex(129) = {'{D^K_{s,r}}'};
M_.endo_names_long(129) = {'regional subsector destuction of capital stock'};
M_.endo_names(130) = {'K_2_1'};
M_.endo_names_tex(130) = {'{K_{s,r}}'};
M_.endo_names_long(130) = {'regional subsector capital'};
M_.endo_names(131) = {'I_AP_2_1'};
M_.endo_names_tex(131) = {'{I^{A,P}_{s,r}}'};
M_.endo_names_long(131) = {'regional subsector private adaptation government expenditure'};
M_.endo_names(132) = {'K_AP_2_1'};
M_.endo_names_tex(132) = {'{K^{A,P}_{s,r}}'};
M_.endo_names_long(132) = {'regional subsector private adaptation capital stock'};
M_.endo_names(133) = {'G_A_2_1'};
M_.endo_names_tex(133) = {'{G^{A}_{s,r}}'};
M_.endo_names_long(133) = {'regional subsector adaptation government expenditure'};
M_.endo_names(134) = {'K_A_2_1'};
M_.endo_names_tex(134) = {'{K^{A}_{s,r}}'};
M_.endo_names_long(134) = {'regional subsector adaptation capital stock'};
M_.endo_names(135) = {'P_2_1'};
M_.endo_names_tex(135) = {'{P_{s,r}}'};
M_.endo_names_long(135) = {'regional subsector price index'};
M_.endo_names(136) = {'Y_2_1'};
M_.endo_names_tex(136) = {'{Y_{s,r}}'};
M_.endo_names_long(136) = {'regional subsector GDP'};
M_.endo_names(137) = {'N_2_1'};
M_.endo_names_tex(137) = {'{N_{s,r}}'};
M_.endo_names_long(137) = {'regional subsector employment'};
M_.endo_names(138) = {'Q_I_2_1'};
M_.endo_names_tex(138) = {'{Q^{I}_{s,r}}'};
M_.endo_names_long(138) = {'regional subsector intermediate inputs'};
M_.endo_names(139) = {'A_2_1'};
M_.endo_names_tex(139) = {'{A_{s,r}}'};
M_.endo_names_long(139) = {'regional subsector TFP'};
M_.endo_names(140) = {'A_N_2_1'};
M_.endo_names_tex(140) = {'{A^{N}_{s,r}}'};
M_.endo_names_long(140) = {'regional subsector labour specific TFP'};
M_.endo_names(141) = {'A_K_2_1'};
M_.endo_names_tex(141) = {'{A^{K}_{s,r}}'};
M_.endo_names_long(141) = {'regional subsector capital specific TFP'};
M_.endo_names(142) = {'Q_A_3'};
M_.endo_names_tex(142) = {'{Q^A_k}'};
M_.endo_names_long(142) = {'sector aggregate output'};
M_.endo_names(143) = {'P_A_3'};
M_.endo_names_tex(143) = {'{P^A_k}'};
M_.endo_names_long(143) = {'sector aggregate price level'};
M_.endo_names(144) = {'KH_3_1'};
M_.endo_names_tex(144) = {'{K_{k,r}}'};
M_.endo_names_long(144) = {'regional sector capital'};
M_.endo_names(145) = {'r_3_1'};
M_.endo_names_tex(145) = {'{r_{k,r}}'};
M_.endo_names_long(145) = {'regional rentqal rate for sector capital'};
M_.endo_names(146) = {'I_3_1'};
M_.endo_names_tex(146) = {'{I_{k,r}}'};
M_.endo_names_long(146) = {'regional sector investment'};
M_.endo_names(147) = {'omegaI_3_1'};
M_.endo_names_tex(147) = {'{\omega^I_{k,r}}'};
M_.endo_names_long(147) = {'shadow value of regional private sector investment'};
M_.endo_names(148) = {'Q_3'};
M_.endo_names_tex(148) = {'{Q_s}'};
M_.endo_names_long(148) = {'sector output'};
M_.endo_names(149) = {'D_3_1'};
M_.endo_names_tex(149) = {'{D_{s,r}}'};
M_.endo_names_long(149) = {'regional subsector damages'};
M_.endo_names(150) = {'D_N_3_1'};
M_.endo_names_tex(150) = {'{D^N_{s,r}}'};
M_.endo_names_long(150) = {'regional subsector damages to labour productivity'};
M_.endo_names(151) = {'D_K_3_1'};
M_.endo_names_tex(151) = {'{D^K_{s,r}}'};
M_.endo_names_long(151) = {'regional subsector destuction of capital stock'};
M_.endo_names(152) = {'K_3_1'};
M_.endo_names_tex(152) = {'{K_{s,r}}'};
M_.endo_names_long(152) = {'regional subsector capital'};
M_.endo_names(153) = {'I_AP_3_1'};
M_.endo_names_tex(153) = {'{I^{A,P}_{s,r}}'};
M_.endo_names_long(153) = {'regional subsector private adaptation government expenditure'};
M_.endo_names(154) = {'K_AP_3_1'};
M_.endo_names_tex(154) = {'{K^{A,P}_{s,r}}'};
M_.endo_names_long(154) = {'regional subsector private adaptation capital stock'};
M_.endo_names(155) = {'G_A_3_1'};
M_.endo_names_tex(155) = {'{G^{A}_{s,r}}'};
M_.endo_names_long(155) = {'regional subsector adaptation government expenditure'};
M_.endo_names(156) = {'K_A_3_1'};
M_.endo_names_tex(156) = {'{K^{A}_{s,r}}'};
M_.endo_names_long(156) = {'regional subsector adaptation capital stock'};
M_.endo_names(157) = {'P_3_1'};
M_.endo_names_tex(157) = {'{P_{s,r}}'};
M_.endo_names_long(157) = {'regional subsector price index'};
M_.endo_names(158) = {'Y_3_1'};
M_.endo_names_tex(158) = {'{Y_{s,r}}'};
M_.endo_names_long(158) = {'regional subsector GDP'};
M_.endo_names(159) = {'N_3_1'};
M_.endo_names_tex(159) = {'{N_{s,r}}'};
M_.endo_names_long(159) = {'regional subsector employment'};
M_.endo_names(160) = {'Q_I_3_1'};
M_.endo_names_tex(160) = {'{Q^{I}_{s,r}}'};
M_.endo_names_long(160) = {'regional subsector intermediate inputs'};
M_.endo_names(161) = {'A_3_1'};
M_.endo_names_tex(161) = {'{A_{s,r}}'};
M_.endo_names_long(161) = {'regional subsector TFP'};
M_.endo_names(162) = {'A_N_3_1'};
M_.endo_names_tex(162) = {'{A^{N}_{s,r}}'};
M_.endo_names_long(162) = {'regional subsector labour specific TFP'};
M_.endo_names(163) = {'A_K_3_1'};
M_.endo_names_tex(163) = {'{A^{K}_{s,r}}'};
M_.endo_names_long(163) = {'regional subsector capital specific TFP'};
M_.endo_partitions = struct();
M_.param_names = cell(169,1);
M_.param_names_tex = cell(169,1);
M_.param_names_long = cell(169,1);
M_.param_names(1) = {'inbsectors_p'};
M_.param_names_tex(1) = {'{K}'};
M_.param_names_long(1) = {'number of sectors'};
M_.param_names(2) = {'inbregions_p'};
M_.param_names_tex(2) = {'{R}'};
M_.param_names_long(2) = {'number of regions'};
M_.param_names(3) = {'lEndogenousY_p'};
M_.param_names_tex(3) = {'{l^{Y}}'};
M_.param_names_long(3) = {'logical indicator for endogenous or exogenous production'};
M_.param_names(4) = {'lCalibration_p'};
M_.param_names_tex(4) = {'{l^{Calib}}'};
M_.param_names_long(4) = {'logical indiactor whether model is calibrated or not'};
M_.param_names(5) = {'substart_1_p'};
M_.param_names_tex(5) = {'substart\_1\_p'};
M_.param_names_long(5) = {'substart_1_p'};
M_.param_names(6) = {'subend_1_p'};
M_.param_names_tex(6) = {'subend\_1\_p'};
M_.param_names_long(6) = {'subend_1_p'};
M_.param_names(7) = {'substart_2_p'};
M_.param_names_tex(7) = {'substart\_2\_p'};
M_.param_names_long(7) = {'substart_2_p'};
M_.param_names(8) = {'subend_2_p'};
M_.param_names_tex(8) = {'subend\_2\_p'};
M_.param_names_long(8) = {'subend_2_p'};
M_.param_names(9) = {'substart_3_p'};
M_.param_names_tex(9) = {'substart\_3\_p'};
M_.param_names_long(9) = {'substart_3_p'};
M_.param_names(10) = {'subend_3_p'};
M_.param_names_tex(10) = {'subend\_3\_p'};
M_.param_names_long(10) = {'subend_3_p'};
M_.param_names(11) = {'omegaQA_1_p'};
M_.param_names_tex(11) = {'{\omega^{Q^A}_{k}}'};
M_.param_names_long(11) = {'distribution parameter for aggregate output from one sector'};
M_.param_names(12) = {'etaQA_1_p'};
M_.param_names_tex(12) = {'{\eta^{Q^A}_{k}}'};
M_.param_names_long(12) = {'elasticity of substitution between products from different subsectors in one sector'};
M_.param_names(13) = {'iGA_1_p'};
M_.param_names_tex(13) = {'{i^{G^A}_s}'};
M_.param_names_long(13) = {'subsector which provides goods for adaptation measures in the respecitve sub-sector'};
M_.param_names(14) = {'iIAP_1_p'};
M_.param_names_tex(14) = {'{i^{A,P}_s}'};
M_.param_names_long(14) = {'subsector which provides goods for private adaptation measures in the respecitve sub-sector'};
M_.param_names(15) = {'phiM_1_p'};
M_.param_names_tex(15) = {'\frac{M_{s,0} \, P^{M}_{k,0}}{P_{0} \, Q_{0}}'};
M_.param_names_long(15) = {'share of sector imports on total output'};
M_.param_names(16) = {'phiX_1_p'};
M_.param_names_tex(16) = {'\frac{X_{s,0} \, P_{k,0}}{P_{k,0} \, Y_{s,0}}'};
M_.param_names_long(16) = {'share of exports on gross value added'};
M_.param_names(17) = {'phiQI_1_p'};
M_.param_names_tex(17) = {'\frac{Q^{I}_{s,0} \, P_{0}}{P_{s,0} \, Q_{s,0}}'};
M_.param_names_long(17) = {'share of intermediate inputs on total subsectoral prodcution'};
M_.param_names(18) = {'D_X_1_p'};
M_.param_names_tex(18) = {'{D^{X}_{s}}'};
M_.param_names_long(18) = {'long-run demand for exports'};
M_.param_names(19) = {'P_M_1_p'};
M_.param_names_tex(19) = {'{P^{M}_{s}}'};
M_.param_names_long(19) = {'long-run price of sector imports'};
M_.param_names(20) = {'P_D_1_p'};
M_.param_names_tex(20) = {'{P^{D}_{s}}'};
M_.param_names_long(20) = {'initial price of sector output'};
M_.param_names(21) = {'omegaM_1_p'};
M_.param_names_tex(21) = {'{\omega^{M}_{k}}'};
M_.param_names_long(21) = {'distribution parameter for imports from one sector'};
M_.param_names(22) = {'omegaQ_1_p'};
M_.param_names_tex(22) = {'{\omega^{Q}_{k}}'};
M_.param_names_long(22) = {'distribution parameter for output from one sector'};
M_.param_names(23) = {'etaQ_1_p'};
M_.param_names_tex(23) = {'{\eta^{Q}_{k}}'};
M_.param_names_long(23) = {'elasticity of substitution between regional production'};
M_.param_names(24) = {'etaI_1_p'};
M_.param_names_tex(24) = {'{\eta^{I}_{k}}'};
M_.param_names_long(24) = {'elasticity of substitution between value added and intermediate products'};
M_.param_names(25) = {'tauKF_1_1_p'};
M_.param_names_tex(25) = {'{\tau^{K,F}_{k,r}}'};
M_.param_names_long(25) = {'region and subsector specific tax rate on capital paid by firms'};
M_.param_names(26) = {'tauNF_1_1_p'};
M_.param_names_tex(26) = {'{\tau^{N,F}_{k,r}}'};
M_.param_names_long(26) = {'region and subsector specific tax rate on labour paid by firms'};
M_.param_names(27) = {'phiY_1_1_p'};
M_.param_names_tex(27) = {'\frac{P_{k,n,0} \, Y_{k,n,0}}{P_{0} \, Y_{0}}'};
M_.param_names_long(27) = {'share of regional and subsectoral output'};
M_.param_names(28) = {'phiYT_1_1_p'};
M_.param_names_tex(28) = {'\frac{P_{k,n,T} \, Y_{k,n,T}}{P_{T} \, Y_{T}}'};
M_.param_names_long(28) = {'terminal share of regional and subsectoral output'};
M_.param_names(29) = {'phiY0_1_1_p'};
M_.param_names_tex(29) = {'\frac{P_{k,n,0} \, Y_{k,n,0}}{P_{0} \, Y_{0}}'};
M_.param_names_long(29) = {'initial share of regional and subsectoral output'};
M_.param_names(30) = {'phiN_1_1_p'};
M_.param_names_tex(30) = {'{N_{k,n,0}}'};
M_.param_names_long(30) = {'long-run share of regional and subsectoral employment'};
M_.param_names(31) = {'phiNT_1_1_p'};
M_.param_names_tex(31) = {'{N_{k,n,T}}'};
M_.param_names_long(31) = {'terminal share of regional and subsectoral employment'};
M_.param_names(32) = {'phiN0_1_1_p'};
M_.param_names_tex(32) = {'{N_{k,n,0}}'};
M_.param_names_long(32) = {'initial share of regional and subsectoral employment'};
M_.param_names(33) = {'phiW_1_1_p'};
M_.param_names_tex(33) = {'\frac{W_{k,n,0} \, N_{k,n,0}}{P_{k,n,0} \, Y_{k,n,0}}'};
M_.param_names_long(33) = {'share of regional and subsectoral employment'};
M_.param_names(34) = {'phiL_1_1_p'};
M_.param_names_tex(34) = {'{\phi^{L}_{k,r}}'};
M_.param_names_long(34) = {'coefficient of disutility to work'};
M_.param_names(35) = {'omegaQ_1_1_p'};
M_.param_names_tex(35) = {'{\omega^{Q}_{k,r}}'};
M_.param_names_long(35) = {'distribution parameter for regional production'};
M_.param_names(36) = {'omegaQI_1_1_p'};
M_.param_names_tex(36) = {'{\omega^{Q^{I}}_{k,r}}'};
M_.param_names_long(36) = {'distribution parameter for intermeditate products'};
M_.param_names(37) = {'alphaK_1_1_p'};
M_.param_names_tex(37) = {'{\alpha^{K}_{k,r}}'};
M_.param_names_long(37) = {'distribution parameter capital share'};
M_.param_names(38) = {'alphaN_1_1_p'};
M_.param_names_tex(38) = {'{\alpha^{N}_{k,r}}'};
M_.param_names_long(38) = {'distribution parameter labour share'};
M_.param_names(39) = {'etaNK_1_1_p'};
M_.param_names_tex(39) = {'{\eta^{N,K}_{k,r}}'};
M_.param_names_long(39) = {'elasticity of substitution between labour and capital'};
M_.param_names(40) = {'A_1_1_p'};
M_.param_names_tex(40) = {'{A_{k,r}}'};
M_.param_names_long(40) = {'subsector long-run TFP'};
M_.param_names(41) = {'deltaKA_1_1_p'};
M_.param_names_tex(41) = {'{\delta^{K^{A}_{k,r}}}'};
M_.param_names_long(41) = {'depreciation rate of adaptation capital stock against landslide'};
M_.param_names(42) = {'gY0_1_1_p'};
M_.param_names_tex(42) = {'{\frac{Y_{2,k,r}}{Y_{1,k,r}}}'};
M_.param_names_long(42) = {'initial subsector growth'};
M_.param_names(43) = {'gN0_1_1_p'};
M_.param_names_tex(43) = {'{\frac{\frac{N_{2,k,r}{N_{2}}}}{\frac{N_{1,k,r}}{N_{1}}}'};
M_.param_names_long(43) = {'initial subsector labour growth'};
M_.param_names(44) = {'omegaA_1_1_p'};
M_.param_names_tex(44) = {'{\omega^{A}_{k,r}}'};
M_.param_names_long(44) = {'exponent for productivity growth'};
M_.param_names(45) = {'A_N_1_1_p'};
M_.param_names_tex(45) = {'{A^{N}_{k,r}}'};
M_.param_names_long(45) = {'subsector labour specific TFP'};
M_.param_names(46) = {'A_K_1_1_p'};
M_.param_names_tex(46) = {'{A^{K}_{k,r}}'};
M_.param_names_long(46) = {'subsector capital specific TFP'};
M_.param_names(47) = {'omegaQA_2_p'};
M_.param_names_tex(47) = {'{\omega^{Q^A}_{k}}'};
M_.param_names_long(47) = {'distribution parameter for aggregate output from one sector'};
M_.param_names(48) = {'etaQA_2_p'};
M_.param_names_tex(48) = {'{\eta^{Q^A}_{k}}'};
M_.param_names_long(48) = {'elasticity of substitution between products from different subsectors in one sector'};
M_.param_names(49) = {'iGA_2_p'};
M_.param_names_tex(49) = {'{i^{G^A}_s}'};
M_.param_names_long(49) = {'subsector which provides goods for adaptation measures in the respecitve sub-sector'};
M_.param_names(50) = {'iIAP_2_p'};
M_.param_names_tex(50) = {'{i^{A,P}_s}'};
M_.param_names_long(50) = {'subsector which provides goods for private adaptation measures in the respecitve sub-sector'};
M_.param_names(51) = {'phiM_2_p'};
M_.param_names_tex(51) = {'\frac{M_{s,0} \, P^{M}_{k,0}}{P_{0} \, Q_{0}}'};
M_.param_names_long(51) = {'share of sector imports on total output'};
M_.param_names(52) = {'phiX_2_p'};
M_.param_names_tex(52) = {'\frac{X_{s,0} \, P_{k,0}}{P_{k,0} \, Y_{s,0}}'};
M_.param_names_long(52) = {'share of exports on gross value added'};
M_.param_names(53) = {'phiQI_2_p'};
M_.param_names_tex(53) = {'\frac{Q^{I}_{s,0} \, P_{0}}{P_{s,0} \, Q_{s,0}}'};
M_.param_names_long(53) = {'share of intermediate inputs on total subsectoral prodcution'};
M_.param_names(54) = {'D_X_2_p'};
M_.param_names_tex(54) = {'{D^{X}_{s}}'};
M_.param_names_long(54) = {'long-run demand for exports'};
M_.param_names(55) = {'P_M_2_p'};
M_.param_names_tex(55) = {'{P^{M}_{s}}'};
M_.param_names_long(55) = {'long-run price of sector imports'};
M_.param_names(56) = {'P_D_2_p'};
M_.param_names_tex(56) = {'{P^{D}_{s}}'};
M_.param_names_long(56) = {'initial price of sector output'};
M_.param_names(57) = {'omegaM_2_p'};
M_.param_names_tex(57) = {'{\omega^{M}_{k}}'};
M_.param_names_long(57) = {'distribution parameter for imports from one sector'};
M_.param_names(58) = {'omegaQ_2_p'};
M_.param_names_tex(58) = {'{\omega^{Q}_{k}}'};
M_.param_names_long(58) = {'distribution parameter for output from one sector'};
M_.param_names(59) = {'etaQ_2_p'};
M_.param_names_tex(59) = {'{\eta^{Q}_{k}}'};
M_.param_names_long(59) = {'elasticity of substitution between regional production'};
M_.param_names(60) = {'etaI_2_p'};
M_.param_names_tex(60) = {'{\eta^{I}_{k}}'};
M_.param_names_long(60) = {'elasticity of substitution between value added and intermediate products'};
M_.param_names(61) = {'tauKF_2_1_p'};
M_.param_names_tex(61) = {'{\tau^{K,F}_{k,r}}'};
M_.param_names_long(61) = {'region and subsector specific tax rate on capital paid by firms'};
M_.param_names(62) = {'tauNF_2_1_p'};
M_.param_names_tex(62) = {'{\tau^{N,F}_{k,r}}'};
M_.param_names_long(62) = {'region and subsector specific tax rate on labour paid by firms'};
M_.param_names(63) = {'phiY_2_1_p'};
M_.param_names_tex(63) = {'\frac{P_{k,n,0} \, Y_{k,n,0}}{P_{0} \, Y_{0}}'};
M_.param_names_long(63) = {'share of regional and subsectoral output'};
M_.param_names(64) = {'phiYT_2_1_p'};
M_.param_names_tex(64) = {'\frac{P_{k,n,T} \, Y_{k,n,T}}{P_{T} \, Y_{T}}'};
M_.param_names_long(64) = {'terminal share of regional and subsectoral output'};
M_.param_names(65) = {'phiY0_2_1_p'};
M_.param_names_tex(65) = {'\frac{P_{k,n,0} \, Y_{k,n,0}}{P_{0} \, Y_{0}}'};
M_.param_names_long(65) = {'initial share of regional and subsectoral output'};
M_.param_names(66) = {'phiN_2_1_p'};
M_.param_names_tex(66) = {'{N_{k,n,0}}'};
M_.param_names_long(66) = {'long-run share of regional and subsectoral employment'};
M_.param_names(67) = {'phiNT_2_1_p'};
M_.param_names_tex(67) = {'{N_{k,n,T}}'};
M_.param_names_long(67) = {'terminal share of regional and subsectoral employment'};
M_.param_names(68) = {'phiN0_2_1_p'};
M_.param_names_tex(68) = {'{N_{k,n,0}}'};
M_.param_names_long(68) = {'initial share of regional and subsectoral employment'};
M_.param_names(69) = {'phiW_2_1_p'};
M_.param_names_tex(69) = {'\frac{W_{k,n,0} \, N_{k,n,0}}{P_{k,n,0} \, Y_{k,n,0}}'};
M_.param_names_long(69) = {'share of regional and subsectoral employment'};
M_.param_names(70) = {'phiL_2_1_p'};
M_.param_names_tex(70) = {'{\phi^{L}_{k,r}}'};
M_.param_names_long(70) = {'coefficient of disutility to work'};
M_.param_names(71) = {'omegaQ_2_1_p'};
M_.param_names_tex(71) = {'{\omega^{Q}_{k,r}}'};
M_.param_names_long(71) = {'distribution parameter for regional production'};
M_.param_names(72) = {'omegaQI_2_1_p'};
M_.param_names_tex(72) = {'{\omega^{Q^{I}}_{k,r}}'};
M_.param_names_long(72) = {'distribution parameter for intermeditate products'};
M_.param_names(73) = {'alphaK_2_1_p'};
M_.param_names_tex(73) = {'{\alpha^{K}_{k,r}}'};
M_.param_names_long(73) = {'distribution parameter capital share'};
M_.param_names(74) = {'alphaN_2_1_p'};
M_.param_names_tex(74) = {'{\alpha^{N}_{k,r}}'};
M_.param_names_long(74) = {'distribution parameter labour share'};
M_.param_names(75) = {'etaNK_2_1_p'};
M_.param_names_tex(75) = {'{\eta^{N,K}_{k,r}}'};
M_.param_names_long(75) = {'elasticity of substitution between labour and capital'};
M_.param_names(76) = {'A_2_1_p'};
M_.param_names_tex(76) = {'{A_{k,r}}'};
M_.param_names_long(76) = {'subsector long-run TFP'};
M_.param_names(77) = {'deltaKA_2_1_p'};
M_.param_names_tex(77) = {'{\delta^{K^{A}_{k,r}}}'};
M_.param_names_long(77) = {'depreciation rate of adaptation capital stock against landslide'};
M_.param_names(78) = {'gY0_2_1_p'};
M_.param_names_tex(78) = {'{\frac{Y_{2,k,r}}{Y_{1,k,r}}}'};
M_.param_names_long(78) = {'initial subsector growth'};
M_.param_names(79) = {'gN0_2_1_p'};
M_.param_names_tex(79) = {'{\frac{\frac{N_{2,k,r}{N_{2}}}}{\frac{N_{1,k,r}}{N_{1}}}'};
M_.param_names_long(79) = {'initial subsector labour growth'};
M_.param_names(80) = {'omegaA_2_1_p'};
M_.param_names_tex(80) = {'{\omega^{A}_{k,r}}'};
M_.param_names_long(80) = {'exponent for productivity growth'};
M_.param_names(81) = {'A_N_2_1_p'};
M_.param_names_tex(81) = {'{A^{N}_{k,r}}'};
M_.param_names_long(81) = {'subsector labour specific TFP'};
M_.param_names(82) = {'A_K_2_1_p'};
M_.param_names_tex(82) = {'{A^{K}_{k,r}}'};
M_.param_names_long(82) = {'subsector capital specific TFP'};
M_.param_names(83) = {'omegaQA_3_p'};
M_.param_names_tex(83) = {'{\omega^{Q^A}_{k}}'};
M_.param_names_long(83) = {'distribution parameter for aggregate output from one sector'};
M_.param_names(84) = {'etaQA_3_p'};
M_.param_names_tex(84) = {'{\eta^{Q^A}_{k}}'};
M_.param_names_long(84) = {'elasticity of substitution between products from different subsectors in one sector'};
M_.param_names(85) = {'iGA_3_p'};
M_.param_names_tex(85) = {'{i^{G^A}_s}'};
M_.param_names_long(85) = {'subsector which provides goods for adaptation measures in the respecitve sub-sector'};
M_.param_names(86) = {'iIAP_3_p'};
M_.param_names_tex(86) = {'{i^{A,P}_s}'};
M_.param_names_long(86) = {'subsector which provides goods for private adaptation measures in the respecitve sub-sector'};
M_.param_names(87) = {'phiM_3_p'};
M_.param_names_tex(87) = {'\frac{M_{s,0} \, P^{M}_{k,0}}{P_{0} \, Q_{0}}'};
M_.param_names_long(87) = {'share of sector imports on total output'};
M_.param_names(88) = {'phiX_3_p'};
M_.param_names_tex(88) = {'\frac{X_{s,0} \, P_{k,0}}{P_{k,0} \, Y_{s,0}}'};
M_.param_names_long(88) = {'share of exports on gross value added'};
M_.param_names(89) = {'phiQI_3_p'};
M_.param_names_tex(89) = {'\frac{Q^{I}_{s,0} \, P_{0}}{P_{s,0} \, Q_{s,0}}'};
M_.param_names_long(89) = {'share of intermediate inputs on total subsectoral prodcution'};
M_.param_names(90) = {'D_X_3_p'};
M_.param_names_tex(90) = {'{D^{X}_{s}}'};
M_.param_names_long(90) = {'long-run demand for exports'};
M_.param_names(91) = {'P_M_3_p'};
M_.param_names_tex(91) = {'{P^{M}_{s}}'};
M_.param_names_long(91) = {'long-run price of sector imports'};
M_.param_names(92) = {'P_D_3_p'};
M_.param_names_tex(92) = {'{P^{D}_{s}}'};
M_.param_names_long(92) = {'initial price of sector output'};
M_.param_names(93) = {'omegaM_3_p'};
M_.param_names_tex(93) = {'{\omega^{M}_{k}}'};
M_.param_names_long(93) = {'distribution parameter for imports from one sector'};
M_.param_names(94) = {'omegaQ_3_p'};
M_.param_names_tex(94) = {'{\omega^{Q}_{k}}'};
M_.param_names_long(94) = {'distribution parameter for output from one sector'};
M_.param_names(95) = {'etaQ_3_p'};
M_.param_names_tex(95) = {'{\eta^{Q}_{k}}'};
M_.param_names_long(95) = {'elasticity of substitution between regional production'};
M_.param_names(96) = {'etaI_3_p'};
M_.param_names_tex(96) = {'{\eta^{I}_{k}}'};
M_.param_names_long(96) = {'elasticity of substitution between value added and intermediate products'};
M_.param_names(97) = {'tauKF_3_1_p'};
M_.param_names_tex(97) = {'{\tau^{K,F}_{k,r}}'};
M_.param_names_long(97) = {'region and subsector specific tax rate on capital paid by firms'};
M_.param_names(98) = {'tauNF_3_1_p'};
M_.param_names_tex(98) = {'{\tau^{N,F}_{k,r}}'};
M_.param_names_long(98) = {'region and subsector specific tax rate on labour paid by firms'};
M_.param_names(99) = {'phiY_3_1_p'};
M_.param_names_tex(99) = {'\frac{P_{k,n,0} \, Y_{k,n,0}}{P_{0} \, Y_{0}}'};
M_.param_names_long(99) = {'share of regional and subsectoral output'};
M_.param_names(100) = {'phiYT_3_1_p'};
M_.param_names_tex(100) = {'\frac{P_{k,n,T} \, Y_{k,n,T}}{P_{T} \, Y_{T}}'};
M_.param_names_long(100) = {'terminal share of regional and subsectoral output'};
M_.param_names(101) = {'phiY0_3_1_p'};
M_.param_names_tex(101) = {'\frac{P_{k,n,0} \, Y_{k,n,0}}{P_{0} \, Y_{0}}'};
M_.param_names_long(101) = {'initial share of regional and subsectoral output'};
M_.param_names(102) = {'phiN_3_1_p'};
M_.param_names_tex(102) = {'{N_{k,n,0}}'};
M_.param_names_long(102) = {'long-run share of regional and subsectoral employment'};
M_.param_names(103) = {'phiNT_3_1_p'};
M_.param_names_tex(103) = {'{N_{k,n,T}}'};
M_.param_names_long(103) = {'terminal share of regional and subsectoral employment'};
M_.param_names(104) = {'phiN0_3_1_p'};
M_.param_names_tex(104) = {'{N_{k,n,0}}'};
M_.param_names_long(104) = {'initial share of regional and subsectoral employment'};
M_.param_names(105) = {'phiW_3_1_p'};
M_.param_names_tex(105) = {'\frac{W_{k,n,0} \, N_{k,n,0}}{P_{k,n,0} \, Y_{k,n,0}}'};
M_.param_names_long(105) = {'share of regional and subsectoral employment'};
M_.param_names(106) = {'phiL_3_1_p'};
M_.param_names_tex(106) = {'{\phi^{L}_{k,r}}'};
M_.param_names_long(106) = {'coefficient of disutility to work'};
M_.param_names(107) = {'omegaQ_3_1_p'};
M_.param_names_tex(107) = {'{\omega^{Q}_{k,r}}'};
M_.param_names_long(107) = {'distribution parameter for regional production'};
M_.param_names(108) = {'omegaQI_3_1_p'};
M_.param_names_tex(108) = {'{\omega^{Q^{I}}_{k,r}}'};
M_.param_names_long(108) = {'distribution parameter for intermeditate products'};
M_.param_names(109) = {'alphaK_3_1_p'};
M_.param_names_tex(109) = {'{\alpha^{K}_{k,r}}'};
M_.param_names_long(109) = {'distribution parameter capital share'};
M_.param_names(110) = {'alphaN_3_1_p'};
M_.param_names_tex(110) = {'{\alpha^{N}_{k,r}}'};
M_.param_names_long(110) = {'distribution parameter labour share'};
M_.param_names(111) = {'etaNK_3_1_p'};
M_.param_names_tex(111) = {'{\eta^{N,K}_{k,r}}'};
M_.param_names_long(111) = {'elasticity of substitution between labour and capital'};
M_.param_names(112) = {'A_3_1_p'};
M_.param_names_tex(112) = {'{A_{k,r}}'};
M_.param_names_long(112) = {'subsector long-run TFP'};
M_.param_names(113) = {'deltaKA_3_1_p'};
M_.param_names_tex(113) = {'{\delta^{K^{A}_{k,r}}}'};
M_.param_names_long(113) = {'depreciation rate of adaptation capital stock against landslide'};
M_.param_names(114) = {'gY0_3_1_p'};
M_.param_names_tex(114) = {'{\frac{Y_{2,k,r}}{Y_{1,k,r}}}'};
M_.param_names_long(114) = {'initial subsector growth'};
M_.param_names(115) = {'gN0_3_1_p'};
M_.param_names_tex(115) = {'{\frac{\frac{N_{2,k,r}{N_{2}}}}{\frac{N_{1,k,r}}{N_{1}}}'};
M_.param_names_long(115) = {'initial subsector labour growth'};
M_.param_names(116) = {'omegaA_3_1_p'};
M_.param_names_tex(116) = {'{\omega^{A}_{k,r}}'};
M_.param_names_long(116) = {'exponent for productivity growth'};
M_.param_names(117) = {'A_N_3_1_p'};
M_.param_names_tex(117) = {'{A^{N}_{k,r}}'};
M_.param_names_long(117) = {'subsector labour specific TFP'};
M_.param_names(118) = {'A_K_3_1_p'};
M_.param_names_tex(118) = {'{A^{K}_{k,r}}'};
M_.param_names_long(118) = {'subsector capital specific TFP'};
M_.param_names(119) = {'beta_p'};
M_.param_names_tex(119) = {'{\beta}'};
M_.param_names_long(119) = {'discount factor'};
M_.param_names(120) = {'omegaP_p'};
M_.param_names_tex(120) = {'{\omega^{P}}'};
M_.param_names_long(120) = {'share of rational agents'};
M_.param_names(121) = {'gamma_p'};
M_.param_names_tex(121) = {'{\gamma}'};
M_.param_names_long(121) = {'preferences for housing in utility function'};
M_.param_names(122) = {'delta_p'};
M_.param_names_tex(122) = {'{\delta}'};
M_.param_names_long(122) = {'capital depreciation rate'};
M_.param_names(123) = {'iGAH_p'};
M_.param_names_tex(123) = {'{i^{G^{A,H}}}'};
M_.param_names_long(123) = {'government housing expenditure sector'};
M_.param_names(124) = {'iIAPH_p'};
M_.param_names_tex(124) = {'{i^{A,P,H}}'};
M_.param_names_long(124) = {'sub sector output used for private housing adaptation expenditure'};
M_.param_names(125) = {'deltaH_p'};
M_.param_names_tex(125) = {'{\delta^H}'};
M_.param_names_long(125) = {'housing depreciation rate'};
M_.param_names(126) = {'deltaKG_p'};
M_.param_names_tex(126) = {'{\delta^{K^{G}}}'};
M_.param_names_long(126) = {'public capital depreciation rate'};
M_.param_names(127) = {'phiG_p'};
M_.param_names_tex(127) = {'{\phi^{G}}'};
M_.param_names_long(127) = {'elasticity of TFP to public capital'};
M_.param_names(128) = {'sigmaL_p'};
M_.param_names_tex(128) = {'{\sigma^{L}}'};
M_.param_names_long(128) = {'inverse Frisch elasticity'};
M_.param_names(129) = {'sigmaC_p'};
M_.param_names_tex(129) = {'{\sigma^{C}}'};
M_.param_names_long(129) = {'intertemporal elasticity of substitution'};
M_.param_names(130) = {'etaQ_p'};
M_.param_names_tex(130) = {'{\eta^{Q}}'};
M_.param_names_long(130) = {'elasticity of substitution between sectoral production'};
M_.param_names(131) = {'etaM_p'};
M_.param_names_tex(131) = {'{\eta^{M}}'};
M_.param_names_long(131) = {'elasticity of substitution between sectoral imports'};
M_.param_names(132) = {'etaF_p'};
M_.param_names_tex(132) = {'{\eta^{F}}'};
M_.param_names_long(132) = {'elasticity of substitution between foreign and domestic products'};
M_.param_names(133) = {'omegaF_p'};
M_.param_names_tex(133) = {'{\omega^{F}}'};
M_.param_names_long(133) = {'distribution parameter between foreign and domestic products'};
M_.param_names(134) = {'phiB_p'};
M_.param_names_tex(134) = {'{\phi^{B}}'};
M_.param_names_long(134) = {'coefficient of foreign adjustment cost'};
M_.param_names(135) = {'phiK_p'};
M_.param_names_tex(135) = {'{\phi^{K}}'};
M_.param_names_long(135) = {'coefficient of investment adjustment cost'};
M_.param_names(136) = {'tauC_p'};
M_.param_names_tex(136) = {'{\tau^{C}}'};
M_.param_names_long(136) = {'consumption tax'};
M_.param_names(137) = {'tauH_p'};
M_.param_names_tex(137) = {'{\tau^{H}}'};
M_.param_names_long(137) = {'tax on housing'};
M_.param_names(138) = {'tauNH_p'};
M_.param_names_tex(138) = {'{\tau^{N,H}}'};
M_.param_names_long(138) = {'labour tax'};
M_.param_names(139) = {'tauKH_p'};
M_.param_names_tex(139) = {'{\tau^{K,H}}'};
M_.param_names_long(139) = {'capital tax'};
M_.param_names(140) = {'etaX_p'};
M_.param_names_tex(140) = {'{\eta^{X}}'};
M_.param_names_long(140) = {'export price elasticity'};
M_.param_names(141) = {'tas0_1_p'};
M_.param_names_tex(141) = {'{tas_{0,r}}'};
M_.param_names_long(141) = {'initial regional tas'};
M_.param_names(142) = {'SfcWind0_1_p'};
M_.param_names_tex(142) = {'{SfcWind_{0,r}}'};
M_.param_names_long(142) = {'initial regional SfcWind'};
M_.param_names(143) = {'pr0_1_p'};
M_.param_names_tex(143) = {'{pr_{0,r}}'};
M_.param_names_long(143) = {'initial regional pr'};
M_.param_names(144) = {'sunshine0_1_p'};
M_.param_names_tex(144) = {'{sunshine_{0,r}}'};
M_.param_names_long(144) = {'initial regional sunshine'};
M_.param_names(145) = {'hurs0_1_p'};
M_.param_names_tex(145) = {'{hurs_{0,r}}'};
M_.param_names_long(145) = {'initial regional hurs'};
M_.param_names(146) = {'heatwave0_1_p'};
M_.param_names_tex(146) = {'{heatwave_{0,r}}'};
M_.param_names_long(146) = {'initial regional heatwave'};
M_.param_names(147) = {'maxdrydays0_1_p'};
M_.param_names_tex(147) = {'{maxdrydays_{0,r}}'};
M_.param_names_long(147) = {'initial regional maxdrydays'};
M_.param_names(148) = {'maxwetdays0_1_p'};
M_.param_names_tex(148) = {'{maxwetdays_{0,r}}'};
M_.param_names_long(148) = {'initial regional maxwetdays'};
M_.param_names(149) = {'storms0_1_p'};
M_.param_names_tex(149) = {'{storms_{0,r}}'};
M_.param_names_long(149) = {'initial regional storms'};
M_.param_names(150) = {'floods0_1_p'};
M_.param_names_tex(150) = {'{floods_{0,r}}'};
M_.param_names_long(150) = {'initial regional floods'};
M_.param_names(151) = {'fire0_1_p'};
M_.param_names_tex(151) = {'{fire_{0,r}}'};
M_.param_names_long(151) = {'initial regional fire'};
M_.param_names(152) = {'landslide0_1_p'};
M_.param_names_tex(152) = {'{landslide_{0,r}}'};
M_.param_names_long(152) = {'initial regional landslide'};
M_.param_names(153) = {'phiQDD_p'};
M_.param_names_tex(153) = {'\frac{Q^{I}_{0} \, P_{0}}{P_{0} \, Q_{0}}'};
M_.param_names_long(153) = {'share of domestically used and produced on total prodcution'};
M_.param_names(154) = {'phiM_p'};
M_.param_names_tex(154) = {'\frac{M_{0} \, P^{M}_{0}}{P_{0} \, Q_{0}}'};
M_.param_names_long(154) = {'share of imports on total prodcution'};
M_.param_names(155) = {'SL0_p'};
M_.param_names_tex(155) = {'{SL_{0}}'};
M_.param_names_long(155) = {'initial SL'};
M_.param_names(156) = {'PoP0_p'};
M_.param_names_tex(156) = {'{POP_0}'};
M_.param_names_long(156) = {'initial population'};
M_.param_names(157) = {'H0_p'};
M_.param_names_tex(157) = {'{H_0}'};
M_.param_names_long(157) = {'initial stocks of houses'};
M_.param_names(158) = {'PH0_p'};
M_.param_names_tex(158) = {'{P^H_0}'};
M_.param_names_long(158) = {'initial price of houses'};
M_.param_names(159) = {'Y0_p'};
M_.param_names_tex(159) = {'{Y_0}'};
M_.param_names_long(159) = {'initial output'};
M_.param_names(160) = {'NX0_p'};
M_.param_names_tex(160) = {'{NX_0}'};
M_.param_names_long(160) = {'initial net export to value added ratio'};
M_.param_names(161) = {'P0_p'};
M_.param_names_tex(161) = {'{P_0}'};
M_.param_names_long(161) = {'initial price level'};
M_.param_names(162) = {'P0_M_p'};
M_.param_names_tex(162) = {'{P^M_0}'};
M_.param_names_long(162) = {'initial price level'};
M_.param_names(163) = {'N0_p'};
M_.param_names_tex(163) = {'{N_0}'};
M_.param_names_long(163) = {'initial employment'};
M_.param_names(164) = {'rf0_p'};
M_.param_names_tex(164) = {'{r^f_0}'};
M_.param_names_long(164) = {'initial world interest rate'};
M_.param_names(165) = {'PoPT_p'};
M_.param_names_tex(165) = {'{PoP_0}'};
M_.param_names_long(165) = {'terminal population'};
M_.param_names(166) = {'YT_p'};
M_.param_names_tex(166) = {'{Y_T}'};
M_.param_names_long(166) = {'terminal output'};
M_.param_names(167) = {'PT_p'};
M_.param_names_tex(167) = {'{P_T}'};
M_.param_names_long(167) = {'terminal price level'};
M_.param_names(168) = {'NT_p'};
M_.param_names_tex(168) = {'{N_T}'};
M_.param_names_long(168) = {'terminal employment'};
M_.param_names(169) = {'sH_p'};
M_.param_names_tex(169) = {'{s^H}'};
M_.param_names_long(169) = {'share for housing investments'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 61;
M_.endo_nbr = 163;
M_.param_nbr = 169;
M_.orig_endo_nbr = 163;
M_.aux_vars = [];
M_.predetermined_variables = [ 78 ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(61, 61);
M_.Correlation_matrix = eye(61, 61);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [1 2 3 4 5 6 9 10 11 15 17 19 20 21 22 23 24 25 26 28 29 30 31 32 33 35 36 37 38 39 40 41 42 43 44 47 48 49 53 55 57 58 59 60 61 62 63 64 66 67 68 69 70 71 72 74 75 76 77 78 79 80 81 82 83 86 87 88 92 94 96 97 98 99 100 101 102 103 105 106 107 108 109 110 111 113 114 115 116 130 131 132 133 134 135 136 137 138 140 141 142 147 149 151 152 153 154 155 156 157 158 159 160 163];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 163;
M_.eq_nbr = 163;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 18 0;
 0 19 0;
 0 20 0;
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 181;
 0 85 182;
 0 86 0;
 0 87 0;
 0 88 183;
 1 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 184;
 2 94 185;
 3 95 0;
 4 96 0;
 0 97 186;
 0 98 187;
 0 99 0;
 0 100 188;
 0 101 0;
 0 102 0;
 0 103 189;
 5 104 0;
 0 105 0;
 0 106 190;
 0 107 0;
 0 108 0;
 0 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 0 116 0;
 6 117 0;
 0 118 191;
 7 119 192;
 0 120 193;
 0 121 0;
 0 122 0;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 8 127 0;
 0 128 0;
 9 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 10 139 0;
 0 140 194;
 11 141 195;
 0 142 196;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 12 149 0;
 0 150 0;
 13 151 0;
 0 152 0;
 0 153 0;
 0 154 0;
 0 155 0;
 0 156 0;
 0 157 0;
 0 158 0;
 0 159 0;
 0 160 0;
 14 161 0;
 0 162 197;
 15 163 198;
 0 164 199;
 0 165 0;
 0 166 0;
 0 167 0;
 0 168 0;
 0 169 0;
 0 170 0;
 16 171 0;
 0 172 0;
 17 173 0;
 0 174 0;
 0 175 0;
 0 176 0;
 0 177 0;
 0 178 0;
 0 179 0;
 0 180 0;]';
M_.nstatic = 131;
M_.nfwrd   = 15;
M_.npred   = 13;
M_.nboth   = 4;
M_.nsfwrd   = 19;
M_.nspred   = 17;
M_.ndynamic   = 32;
M_.dynamic_tmp_nbr = [181; 309; 190; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'domestic aggregate sector output' ;
  2 , 'name' , 'domestic demand for aggregate sector output' ;
  3 , 'mcp' , 'K_1_1>0' ;
  3 , 'name' , 'HH FOC capital' ;
  4 , 'mcp' , 'I_1_1 > 0' ;
  4 , 'name' , 'HH FOC investment' ;
  5 , 'mcp' , 'I_1_1 > 0' ;
  5 , 'name' , 'LOM capital' ;
  6 , 'mcp' , 'I_1_1 > 0' ;
  6 , 'name' , 'households aggregate capital' ;
  7 , 'name' , 'subsector specific corporate tax rate paid by firms' ;
  8 , 'name' , 'subsector specific labour tax rate paid by firms' ;
  9 , 'name' , 'subsector specific TFP' ;
  10 , 'name' , 'subsector and capital specific productivity shock' ;
  11 , 'name' , 'subsector and labour specific productivity shock' ;
  12 , 'name' , 'subsector specific damage function' ;
  13 , 'name' , 'subsector specific damage function on labour productivity' ;
  14 , 'name' , 'subsector specific damage function on capital formation' ;
  15 , 'name' , 'subsector specific adaptation expenditures by households against climate change' ;
  16 , 'name' , 'subsector specific private adaptation capital against climate change' ;
  17 , 'name' , 'subsector specific adaptation expenditures by the government against climate change' ;
  18 , 'name' , 'subsector specific adaptation capital against climate change' ;
  19 , 'name' , 'demand for regional subsector output' ;
  20 , 'name' , 'demand for regional subsector value added' ;
  21 , 'name' , 'regional subsector demand for intermediates' ;
  22 , 'name' , 'subsector specific output' ;
  23 , 'mcp' , 'K_1_1 > 0' ;
  23 , 'name' , 'Firms FOC capital' ;
  24 , 'mcp' , 'N_1_1 > 0' ;
  24 , 'name' , 'Firms FOC labour' ;
  25 , 'mcp' , 'N_1_1>0' ;
  25 , 'name' , 'HH FOC labour' ;
  26 , 'name' , 'subsector region specific output' ;
  27 , 'name' , 'aggregate sectoral investment' ;
  28 , 'name' , 'demand for subsector imports' ;
  29 , 'name' , 'use of domestic subsector produced products' ;
  30 , 'name' , 'domestic subsector produced products' ;
  31 , 'name' , 'intermediate products demanded from subsector' ;
  32 , 'name' , 'domestic demand for subsector output' ;
  33 , 'name' , 'subsector aggregate specific value added' ;
  34 , 'name' , 'aggergate subsector labour' ;
  35 , 'name' , 'aggergate subsector labour income' ;
  36 , 'name' , 'aggregate subsector capital' ;
  37 , 'name' , 'domestic subsector exports' ;
  38 , 'name' , 'demand for domestic subsector exports' ;
  39 , 'name' , 'domestic aggregate sector output' ;
  40 , 'name' , 'domestic demand for aggregate sector output' ;
  41 , 'mcp' , 'K_2_1>0' ;
  41 , 'name' , 'HH FOC capital' ;
  42 , 'mcp' , 'I_2_1 > 0' ;
  42 , 'name' , 'HH FOC investment' ;
  43 , 'mcp' , 'I_2_1 > 0' ;
  43 , 'name' , 'LOM capital' ;
  44 , 'mcp' , 'I_2_1 > 0' ;
  44 , 'name' , 'households aggregate capital' ;
  45 , 'name' , 'subsector specific corporate tax rate paid by firms' ;
  46 , 'name' , 'subsector specific labour tax rate paid by firms' ;
  47 , 'name' , 'subsector specific TFP' ;
  48 , 'name' , 'subsector and capital specific productivity shock' ;
  49 , 'name' , 'subsector and labour specific productivity shock' ;
  50 , 'name' , 'subsector specific damage function' ;
  51 , 'name' , 'subsector specific damage function on labour productivity' ;
  52 , 'name' , 'subsector specific damage function on capital formation' ;
  53 , 'name' , 'subsector specific adaptation expenditures by households against climate change' ;
  54 , 'name' , 'subsector specific private adaptation capital against climate change' ;
  55 , 'name' , 'subsector specific adaptation expenditures by the government against climate change' ;
  56 , 'name' , 'subsector specific adaptation capital against climate change' ;
  57 , 'name' , 'demand for regional subsector output' ;
  58 , 'name' , 'demand for regional subsector value added' ;
  59 , 'name' , 'regional subsector demand for intermediates' ;
  60 , 'name' , 'subsector specific output' ;
  61 , 'mcp' , 'K_2_1 > 0' ;
  61 , 'name' , 'Firms FOC capital' ;
  62 , 'mcp' , 'N_2_1 > 0' ;
  62 , 'name' , 'Firms FOC labour' ;
  63 , 'mcp' , 'N_2_1>0' ;
  63 , 'name' , 'HH FOC labour' ;
  64 , 'name' , 'subsector region specific output' ;
  65 , 'name' , 'aggregate sectoral investment' ;
  66 , 'name' , 'subsectoral price for imports' ;
  67 , 'name' , 'demand for subsector imports' ;
  68 , 'name' , 'use of domestic subsector produced products' ;
  69 , 'name' , 'domestic subsector produced products' ;
  70 , 'name' , 'intermediate products demanded from subsector' ;
  71 , 'name' , 'domestic demand for subsector output' ;
  72 , 'name' , 'subsector aggregate specific value added' ;
  73 , 'name' , 'aggergate subsector labour' ;
  74 , 'name' , 'aggergate subsector labour income' ;
  75 , 'name' , 'aggregate subsector capital' ;
  76 , 'name' , 'domestic subsector exports' ;
  77 , 'name' , 'demand for domestic subsector exports' ;
  78 , 'name' , 'domestic aggregate sector output' ;
  79 , 'name' , 'domestic demand for aggregate sector output' ;
  80 , 'mcp' , 'K_3_1>0' ;
  80 , 'name' , 'HH FOC capital' ;
  81 , 'mcp' , 'I_3_1 > 0' ;
  81 , 'name' , 'HH FOC investment' ;
  82 , 'mcp' , 'I_3_1 > 0' ;
  82 , 'name' , 'LOM capital' ;
  83 , 'mcp' , 'I_3_1 > 0' ;
  83 , 'name' , 'households aggregate capital' ;
  84 , 'name' , 'subsector specific corporate tax rate paid by firms' ;
  85 , 'name' , 'subsector specific labour tax rate paid by firms' ;
  86 , 'name' , 'subsector specific TFP' ;
  87 , 'name' , 'subsector and capital specific productivity shock' ;
  88 , 'name' , 'subsector and labour specific productivity shock' ;
  89 , 'name' , 'subsector specific damage function' ;
  90 , 'name' , 'subsector specific damage function on labour productivity' ;
  91 , 'name' , 'subsector specific damage function on capital formation' ;
  92 , 'name' , 'subsector specific adaptation expenditures by households against climate change' ;
  93 , 'name' , 'subsector specific private adaptation capital against climate change' ;
  94 , 'name' , 'subsector specific adaptation expenditures by the government against climate change' ;
  95 , 'name' , 'subsector specific adaptation capital against climate change' ;
  96 , 'name' , 'demand for regional subsector output' ;
  97 , 'name' , 'demand for regional subsector value added' ;
  98 , 'name' , 'regional subsector demand for intermediates' ;
  99 , 'name' , 'subsector specific output' ;
  100 , 'mcp' , 'K_3_1 > 0' ;
  100 , 'name' , 'Firms FOC capital' ;
  101 , 'mcp' , 'N_3_1 > 0' ;
  101 , 'name' , 'Firms FOC labour' ;
  102 , 'mcp' , 'N_3_1>0' ;
  102 , 'name' , 'HH FOC labour' ;
  103 , 'name' , 'subsector region specific output' ;
  104 , 'name' , 'aggregate sectoral investment' ;
  105 , 'name' , 'subsectoral price for imports' ;
  106 , 'name' , 'demand for subsector imports' ;
  107 , 'name' , 'use of domestic subsector produced products' ;
  108 , 'name' , 'domestic subsector produced products' ;
  109 , 'name' , 'intermediate products demanded from subsector' ;
  110 , 'name' , 'domestic demand for subsector output' ;
  111 , 'name' , 'subsector aggregate specific value added' ;
  112 , 'name' , 'aggergate subsector labour' ;
  113 , 'name' , 'aggergate subsector labour income' ;
  114 , 'name' , 'aggregate subsector capital' ;
  115 , 'name' , 'domestic subsector exports' ;
  116 , 'name' , 'demand for domestic subsector exports' ;
  117 , 'name' , 'tas' ;
  118 , 'name' , 'SfcWind' ;
  119 , 'name' , 'pr' ;
  120 , 'name' , 'sunshine' ;
  121 , 'name' , 'hurs' ;
  122 , 'name' , 'heatwave' ;
  123 , 'name' , 'maxdrydays' ;
  124 , 'name' , 'maxwetdays' ;
  125 , 'name' , 'storms' ;
  126 , 'name' , 'floods' ;
  127 , 'name' , 'fire' ;
  128 , 'name' , 'landslide' ;
  129 , 'name' , 'SL' ;
  130 , 'name' , 'aggregate output' ;
  131 , 'name' , 'domestic output used domestically' ;
  132 , 'name' , 'output used domestically' ;
  133 , 'name' , 'aggregate gross value added' ;
  134 , 'name' , 'aggregate intermediate input' ;
  135 , 'name' , 'aggregate investment' ;
  136 , 'name' , 'Exports' ;
  137 , 'name' , 'Imports' ;
  138 , 'name' , 'aggregate capital' ;
  139 , 'name' , 'aggregate labour' ;
  140 , 'name' , 'demand for imports' ;
  141 , 'name' , 'demand for domestic produced products' ;
  142 , 'name' , 'Resource Constraint' ;
  143 , 'name' , 'taxes on household labour income' ;
  144 , 'name' , 'taxes on household capital income' ;
  145 , 'name' , 'taxes on consumption' ;
  146 , 'name' , 'taxes on housing' ;
  147 , 'name' , 'national price level' ;
  148 , 'name' , 'import price' ;
  149 , 'name' , 'net exports' ;
  150 , 'name' , 'world interest rate' ;
  151 , 'name' , 'FOC HH consumption' ;
  152 , 'name' , 'law of motion for houses' ;
  153 , 'name' , 'exogenous development of housing prices' ;
  154 , 'name' , 'damages to houses' ;
  155 , 'name' , 'FOC HH houses' ;
  156 , 'name' , 'FOC HH investment in houses' ;
  157 , 'name' , 'Foreign Assets' ;
  158 , 'name' , 'adaptation measures for housing stock' ;
  159 , 'name' , 'private adaptation measures for housing stock' ;
  160 , 'name' , 'Government Budget Constraint' ;
  161 , 'name' , 'public goods capital stock' ;
  162 , 'name' , 'Government foreign debt' ;
  163 , 'name' , 'Population' ;
};
M_.mapping.K.eqidx = [138 ];
M_.mapping.N.eqidx = [139 ];
M_.mapping.SL.eqidx = [129 ];
M_.mapping.tas_1.eqidx = [117 ];
M_.mapping.SfcWind_1.eqidx = [118 ];
M_.mapping.pr_1.eqidx = [119 ];
M_.mapping.sunshine_1.eqidx = [120 ];
M_.mapping.hurs_1.eqidx = [121 ];
M_.mapping.heatwave_1.eqidx = [122 ];
M_.mapping.maxdrydays_1.eqidx = [123 ];
M_.mapping.maxwetdays_1.eqidx = [124 ];
M_.mapping.storms_1.eqidx = [125 ];
M_.mapping.floods_1.eqidx = [126 ];
M_.mapping.fire_1.eqidx = [127 ];
M_.mapping.landslide_1.eqidx = [128 ];
M_.mapping.I_1.eqidx = [27 135 ];
M_.mapping.Y_1.eqidx = [33 ];
M_.mapping.Q_D_1.eqidx = [1 29 32 ];
M_.mapping.Q_I_1.eqidx = [31 134 ];
M_.mapping.M_1.eqidx = [28 137 ];
M_.mapping.X_1.eqidx = [29 37 38 136 ];
M_.mapping.D_X_1.eqidx = [38 ];
M_.mapping.K_1.eqidx = [36 138 ];
M_.mapping.N_1.eqidx = [34 35 139 ];
M_.mapping.P_D_1.eqidx = [1 19 30 32 37 130 136 142 160 ];
M_.mapping.P_M_1.eqidx = [28 37 137 ];
M_.mapping.W_1.eqidx = [35 ];
M_.mapping.Q_1_1.eqidx = [19 20 21 26 30 ];
M_.mapping.W_1_1.eqidx = [24 25 35 160 ];
M_.mapping.tauKF_1_1.eqidx = [7 23 160 ];
M_.mapping.tauNF_1_1.eqidx = [8 24 160 ];
M_.mapping.P_D_1_1.eqidx = [19 20 21 30 ];
M_.mapping.I_2.eqidx = [65 135 ];
M_.mapping.Y_2.eqidx = [72 ];
M_.mapping.Q_D_2.eqidx = [39 68 71 ];
M_.mapping.Q_I_2.eqidx = [70 134 ];
M_.mapping.M_2.eqidx = [67 137 ];
M_.mapping.X_2.eqidx = [68 76 77 136 ];
M_.mapping.D_X_2.eqidx = [77 ];
M_.mapping.K_2.eqidx = [75 138 ];
M_.mapping.N_2.eqidx = [73 74 139 ];
M_.mapping.P_D_2.eqidx = [39 57 69 71 76 130 136 142 160 ];
M_.mapping.P_M_2.eqidx = [66 67 76 137 ];
M_.mapping.W_2.eqidx = [74 ];
M_.mapping.Q_2_1.eqidx = [57 58 59 64 69 ];
M_.mapping.W_2_1.eqidx = [62 63 74 160 ];
M_.mapping.tauKF_2_1.eqidx = [45 61 160 ];
M_.mapping.tauNF_2_1.eqidx = [46 62 160 ];
M_.mapping.P_D_2_1.eqidx = [57 58 59 69 ];
M_.mapping.I_3.eqidx = [104 135 ];
M_.mapping.Y_3.eqidx = [111 ];
M_.mapping.Q_D_3.eqidx = [78 107 110 ];
M_.mapping.Q_I_3.eqidx = [109 134 ];
M_.mapping.M_3.eqidx = [106 137 ];
M_.mapping.X_3.eqidx = [107 115 116 136 ];
M_.mapping.D_X_3.eqidx = [116 ];
M_.mapping.K_3.eqidx = [114 138 ];
M_.mapping.N_3.eqidx = [112 113 139 ];
M_.mapping.P_D_3.eqidx = [78 96 108 110 115 130 136 142 160 ];
M_.mapping.P_M_3.eqidx = [105 106 115 137 ];
M_.mapping.W_3.eqidx = [113 ];
M_.mapping.Q_3_1.eqidx = [96 97 98 103 108 ];
M_.mapping.W_3_1.eqidx = [101 102 113 160 ];
M_.mapping.tauKF_3_1.eqidx = [84 100 160 ];
M_.mapping.tauNF_3_1.eqidx = [85 101 160 ];
M_.mapping.P_D_3_1.eqidx = [96 97 98 108 ];
M_.mapping.P.eqidx = [3 4 6 15 17 21 29 31 36 41 42 44 53 55 59 68 70 75 80 81 83 92 94 98 107 109 114 132 133 134 135 138 140 141 142 147 149 151 154 158 159 160 ];
M_.mapping.lambda.eqidx = [3 4 25 41 42 63 80 81 102 151 155 156 157 ];
M_.mapping.P_D.eqidx = [2 40 79 130 131 132 136 141 142 149 ];
M_.mapping.P_M.eqidx = [28 66 67 105 106 132 137 140 148 149 ];
M_.mapping.C.eqidx = [4 42 81 142 151 155 160 ];
M_.mapping.H.eqidx = [151 152 155 ];
M_.mapping.IH.eqidx = [142 152 160 ];
M_.mapping.PH.eqidx = [142 153 154 156 160 ];
M_.mapping.DH.eqidx = [152 154 ];
M_.mapping.omegaH.eqidx = [155 156 ];
M_.mapping.PoP.eqidx = [4 5 22 24 42 43 60 62 81 82 99 101 151 152 155 160 163 ];
M_.mapping.B.eqidx = [157 160 ];
M_.mapping.BG.eqidx = [157 160 162 ];
M_.mapping.NX.eqidx = [142 149 157 160 ];
M_.mapping.rf.eqidx = [150 157 160 ];
M_.mapping.G.eqidx = [142 160 161 ];
M_.mapping.tauC.eqidx = [4 42 81 145 151 160 ];
M_.mapping.tauH.eqidx = [146 156 160 ];
M_.mapping.tauNH.eqidx = [25 63 102 143 160 ];
M_.mapping.tauKH.eqidx = [3 41 80 144 160 ];
M_.mapping.KG.eqidx = [9 47 86 161 ];
M_.mapping.I.eqidx = [135 142 ];
M_.mapping.Y.eqidx = [133 154 157 160 ];
M_.mapping.Q_U.eqidx = [132 140 141 ];
M_.mapping.Q_D.eqidx = [2 40 79 131 132 141 ];
M_.mapping.Q_I.eqidx = [134 142 ];
M_.mapping.Q.eqidx = [130 142 ];
M_.mapping.M.eqidx = [28 67 106 132 137 140 149 ];
M_.mapping.X.eqidx = [136 149 ];
M_.mapping.G_A_DH.eqidx = [29 68 107 142 158 160 ];
M_.mapping.I_AP_DH.eqidx = [29 68 107 142 159 ];
M_.mapping.Q_A_1.eqidx = [1 2 32 131 ];
M_.mapping.P_A_1.eqidx = [1 2 32 131 ];
M_.mapping.KH_1_1.eqidx = [5 6 ];
M_.mapping.r_1_1.eqidx = [3 23 160 ];
M_.mapping.I_1_1.eqidx = [4 5 27 ];
M_.mapping.omegaI_1_1.eqidx = [3 4 ];
M_.mapping.Q_1.eqidx = [19 29 30 38 130 ];
M_.mapping.D_1_1.eqidx = [12 22 23 24 ];
M_.mapping.D_N_1_1.eqidx = [13 22 24 ];
M_.mapping.D_K_1_1.eqidx = [5 14 ];
M_.mapping.K_1_1.eqidx = [6 22 23 36 160 ];
M_.mapping.I_AP_1_1.eqidx = [16 29 68 107 142 ];
M_.mapping.K_AP_1_1.eqidx = [15 16 ];
M_.mapping.G_A_1_1.eqidx = [18 29 68 107 142 160 ];
M_.mapping.K_A_1_1.eqidx = [17 18 ];
M_.mapping.P_1_1.eqidx = [6 20 24 33 36 133 160 ];
M_.mapping.Y_1_1.eqidx = [20 22 23 24 26 33 133 ];
M_.mapping.N_1_1.eqidx = [22 24 25 34 35 160 ];
M_.mapping.Q_I_1_1.eqidx = [21 26 31 ];
M_.mapping.A_1_1.eqidx = [9 22 23 24 ];
M_.mapping.A_N_1_1.eqidx = [11 22 24 25 ];
M_.mapping.A_K_1_1.eqidx = [10 22 23 ];
M_.mapping.Q_A_2.eqidx = [39 40 71 131 ];
M_.mapping.P_A_2.eqidx = [39 40 71 131 ];
M_.mapping.KH_2_1.eqidx = [43 44 ];
M_.mapping.r_2_1.eqidx = [41 61 160 ];
M_.mapping.I_2_1.eqidx = [42 43 65 ];
M_.mapping.omegaI_2_1.eqidx = [41 42 ];
M_.mapping.Q_2.eqidx = [57 68 69 77 130 ];
M_.mapping.D_2_1.eqidx = [50 60 61 62 ];
M_.mapping.D_N_2_1.eqidx = [51 60 62 ];
M_.mapping.D_K_2_1.eqidx = [43 52 ];
M_.mapping.K_2_1.eqidx = [44 60 61 75 160 ];
M_.mapping.I_AP_2_1.eqidx = [29 54 68 107 142 ];
M_.mapping.K_AP_2_1.eqidx = [53 54 ];
M_.mapping.G_A_2_1.eqidx = [29 56 68 107 142 160 ];
M_.mapping.K_A_2_1.eqidx = [55 56 ];
M_.mapping.P_2_1.eqidx = [44 58 62 72 75 133 160 ];
M_.mapping.Y_2_1.eqidx = [58 60 61 62 64 72 133 ];
M_.mapping.N_2_1.eqidx = [60 62 63 73 74 160 ];
M_.mapping.Q_I_2_1.eqidx = [59 64 70 ];
M_.mapping.A_2_1.eqidx = [47 60 61 62 ];
M_.mapping.A_N_2_1.eqidx = [49 60 62 63 ];
M_.mapping.A_K_2_1.eqidx = [48 60 61 ];
M_.mapping.Q_A_3.eqidx = [78 79 110 131 ];
M_.mapping.P_A_3.eqidx = [78 79 110 131 ];
M_.mapping.KH_3_1.eqidx = [82 83 ];
M_.mapping.r_3_1.eqidx = [80 100 160 ];
M_.mapping.I_3_1.eqidx = [81 82 104 ];
M_.mapping.omegaI_3_1.eqidx = [80 81 ];
M_.mapping.Q_3.eqidx = [96 107 108 116 130 ];
M_.mapping.D_3_1.eqidx = [89 99 100 101 ];
M_.mapping.D_N_3_1.eqidx = [90 99 101 ];
M_.mapping.D_K_3_1.eqidx = [82 91 ];
M_.mapping.K_3_1.eqidx = [83 99 100 114 160 ];
M_.mapping.I_AP_3_1.eqidx = [29 68 93 107 142 ];
M_.mapping.K_AP_3_1.eqidx = [92 93 ];
M_.mapping.G_A_3_1.eqidx = [29 68 95 107 142 160 ];
M_.mapping.K_A_3_1.eqidx = [94 95 ];
M_.mapping.P_3_1.eqidx = [83 97 101 111 114 133 160 ];
M_.mapping.Y_3_1.eqidx = [97 99 100 101 103 111 133 ];
M_.mapping.N_3_1.eqidx = [99 101 102 112 113 160 ];
M_.mapping.Q_I_3_1.eqidx = [98 103 109 ];
M_.mapping.A_3_1.eqidx = [86 99 100 101 ];
M_.mapping.A_N_3_1.eqidx = [88 99 101 102 ];
M_.mapping.A_K_3_1.eqidx = [87 99 100 ];
M_.mapping.exo_tauC.eqidx = [145 ];
M_.mapping.exo_tauH.eqidx = [146 ];
M_.mapping.exo_tauNH.eqidx = [143 ];
M_.mapping.exo_tauKH.eqidx = [144 ];
M_.mapping.exo_H.eqidx = [153 ];
M_.mapping.exo_DH.eqidx = [154 ];
M_.mapping.exo_PoP.eqidx = [163 ];
M_.mapping.exo_BG.eqidx = [162 ];
M_.mapping.exo_rf.eqidx = [150 ];
M_.mapping.exo_P.eqidx = [147 ];
M_.mapping.exo_M.eqidx = [148 ];
M_.mapping.exo_X_1.eqidx = [37 ];
M_.mapping.exo_1_1.eqidx = [9 ];
M_.mapping.exo_N_1_1.eqidx = [11 ];
M_.mapping.exo_K_1_1.eqidx = [10 ];
M_.mapping.exo_D_1_1.eqidx = [12 ];
M_.mapping.exo_D_N_1_1.eqidx = [13 ];
M_.mapping.exo_D_K_1_1.eqidx = [14 ];
M_.mapping.exo_tauKF_1_1.eqidx = [7 ];
M_.mapping.exo_tauNF_1_1.eqidx = [8 ];
M_.mapping.exo_GA_1_1.eqidx = [17 ];
M_.mapping.exo_IAP_1_1.eqidx = [15 ];
M_.mapping.exo_X_2.eqidx = [76 ];
M_.mapping.exo_M_2.eqidx = [66 ];
M_.mapping.exo_2_1.eqidx = [47 ];
M_.mapping.exo_N_2_1.eqidx = [49 ];
M_.mapping.exo_K_2_1.eqidx = [48 ];
M_.mapping.exo_D_2_1.eqidx = [50 ];
M_.mapping.exo_D_N_2_1.eqidx = [51 ];
M_.mapping.exo_D_K_2_1.eqidx = [52 ];
M_.mapping.exo_tauKF_2_1.eqidx = [45 ];
M_.mapping.exo_tauNF_2_1.eqidx = [46 ];
M_.mapping.exo_GA_2_1.eqidx = [55 ];
M_.mapping.exo_IAP_2_1.eqidx = [53 ];
M_.mapping.exo_X_3.eqidx = [115 ];
M_.mapping.exo_M_3.eqidx = [105 ];
M_.mapping.exo_3_1.eqidx = [86 ];
M_.mapping.exo_N_3_1.eqidx = [88 ];
M_.mapping.exo_K_3_1.eqidx = [87 ];
M_.mapping.exo_D_3_1.eqidx = [89 ];
M_.mapping.exo_D_N_3_1.eqidx = [90 ];
M_.mapping.exo_D_K_3_1.eqidx = [91 ];
M_.mapping.exo_tauKF_3_1.eqidx = [84 ];
M_.mapping.exo_tauNF_3_1.eqidx = [85 ];
M_.mapping.exo_GA_3_1.eqidx = [94 ];
M_.mapping.exo_IAP_3_1.eqidx = [92 ];
M_.mapping.exo_G_A_DH.eqidx = [158 ];
M_.mapping.exo_I_AP_DH.eqidx = [159 ];
M_.mapping.exo_SL.eqidx = [129 ];
M_.mapping.exo_tas_1.eqidx = [117 ];
M_.mapping.exo_SfcWind_1.eqidx = [118 ];
M_.mapping.exo_pr_1.eqidx = [119 ];
M_.mapping.exo_sunshine_1.eqidx = [120 ];
M_.mapping.exo_hurs_1.eqidx = [121 ];
M_.mapping.exo_heatwave_1.eqidx = [122 ];
M_.mapping.exo_maxdrydays_1.eqidx = [123 ];
M_.mapping.exo_maxwetdays_1.eqidx = [124 ];
M_.mapping.exo_storms_1.eqidx = [125 ];
M_.mapping.exo_floods_1.eqidx = [126 ];
M_.mapping.exo_fire_1.eqidx = [127 ];
M_.mapping.exo_landslide_1.eqidx = [128 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [72 77 78 79 87 100 102 110 112 122 124 132 134 144 146 154 156 ];
M_.exo_names_orig_ord = [1:61];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(163, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(61, 1);
M_.params = NaN(169, 1);
M_.endo_trends = struct('deflator', cell(163, 1), 'log_deflator', cell(163, 1), 'growth_factor', cell(163, 1), 'log_growth_factor', cell(163, 1));
M_.NNZDerivatives = [750; 2120; -1; ];
M_.static_tmp_nbr = [124; 82; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
options_.iStepSteadyState = 1;
options_.iStepSimulation  = 10;
sWorkbookNameInput = ['ExcelFiles/ModelSimulationandCalibration' num2str(3) 'Sectorsand' num2str(1) 'Regions' sSensitivity '.xlsx'];
sWorkbookNameOutput = ['ExcelFiles/ResultsScenarios' num2str(3) 'Sectorsand' num2str(1)  'Regions' sSensitivity '.xlsx'];
M_.ClimateVarsRegional = '[tas, SfcWind, pr, sunshine, hurs, heatwave, maxdrydays, maxwetdays, storms, floods, fire, landslide]';
M_.ClimateVarsNational = '[SL]';
M_.params(1) = 3;
inbsectors_p = M_.params(1);
M_.params(3) = 1;
lEndogenousY_p = M_.params(3);
M_.params(5) = 1;
substart_1_p = M_.params(5);
M_.params(6) = 1;
subend_1_p = M_.params(6);
M_.params(7) = 2;
substart_2_p = M_.params(7);
M_.params(8) = 2;
subend_2_p = M_.params(8);
M_.params(9) = 3;
substart_3_p = M_.params(9);
M_.params(10) = 3;
subend_3_p = M_.params(10);
M_.params(2) = 1;
inbregions_p = M_.params(2);
M_.params(120) = 1;
omegaP_p = M_.params(120);
M_.params(140) = 0.61;
etaX_p = M_.params(140);
M_.params(130) = 1.04;
etaQ_p = M_.params(130);
M_.params(136) = 0.1;
tauC_p = M_.params(136);
M_.params(137) = 0.05;
tauH_p = M_.params(137);
M_.params(138) = 0.2;
tauNH_p = M_.params(138);
M_.params(139) = 0.2;
tauKH_p = M_.params(139);
M_.params(119) = 0.95;
beta_p = M_.params(119);
M_.params(122) = 0.05;
delta_p = M_.params(122);
M_.params(125) = 0.05;
deltaH_p = M_.params(125);
M_.params(121) = 0.05;
gamma_p = M_.params(121);
M_.params(126) = 0.1;
deltaKG_p = M_.params(126);
M_.params(127) = 0;
phiG_p = M_.params(127);
M_.params(128) = 0.25;
sigmaL_p = M_.params(128);
M_.params(129) = 1;
sigmaC_p = M_.params(129);
rhoA_p = 0.9;
M_.params(133) = 0.5;
omegaF_p = M_.params(133);
M_.params(132) = 0.75;
etaF_p = M_.params(132);
M_.params(131) = 1.01;
etaM_p = M_.params(131);
M_.params(156) = 95;
PoP0_p = M_.params(156);
M_.params(159) = 1;
Y0_p = M_.params(159);
M_.params(157) = 23;
H0_p = M_.params(157);
M_.params(158) = 1;
PH0_p = M_.params(158);
M_.params(162) = 1;
P0_M_p = M_.params(162);
M_.params(160) = 0;
NX0_p = M_.params(160);
M_.params(163) = 0.15;
N0_p = M_.params(163);
M_.params(168) = M_.params(163);
NT_p = M_.params(168);
M_.params(161) = 1;
P0_p = M_.params(161);
M_.params(165) = M_.params(156);
PoPT_p = M_.params(165);
M_.params(166) = M_.params(159);
YT_p = M_.params(166);
M_.params(167) = M_.params(159);
PT_p = M_.params(167);
M_.params(134) = 10;
phiB_p = M_.params(134);
M_.params(135) = 10;
phiK_p = M_.params(135);
M_.params(154) = 0.45;
phiM_p = M_.params(154);
M_.params(153) = 0.5;
phiQDD_p = M_.params(153);
M_.params(123) = 0;
iGAH_p = M_.params(123);
M_.params(124) = 0;
iIAPH_p = M_.params(124);
M_.params(155) = 0;
SL0_p = M_.params(155);
SLT_p = SL0_p;
M_.params(141) = 0;
tas0_1_p = M_.params(141);
tasT_1_p = tas0_1_p;
M_.params(142) = 0;
SfcWind0_1_p = M_.params(142);
SfcWindT_1_p = SfcWind0_1_p;
M_.params(143) = 0;
pr0_1_p = M_.params(143);
prT_1_p = pr0_1_p;
M_.params(144) = 0;
sunshine0_1_p = M_.params(144);
sunshineT_1_p = sunshine0_1_p;
M_.params(145) = 0;
hurs0_1_p = M_.params(145);
hursT_1_p = hurs0_1_p;
M_.params(146) = 0;
heatwave0_1_p = M_.params(146);
heatwaveT_1_p = heatwave0_1_p;
M_.params(147) = 0;
maxdrydays0_1_p = M_.params(147);
maxdrydaysT_1_p = maxdrydays0_1_p;
M_.params(148) = 0;
maxwetdays0_1_p = M_.params(148);
maxwetdaysT_1_p = maxwetdays0_1_p;
M_.params(149) = 0;
storms0_1_p = M_.params(149);
stormsT_1_p = storms0_1_p;
M_.params(150) = 0;
floods0_1_p = M_.params(150);
floodsT_1_p = floods0_1_p;
M_.params(151) = 0;
fire0_1_p = M_.params(151);
fireT_1_p = fire0_1_p;
M_.params(152) = 0;
landslide0_1_p = M_.params(152);
landslideT_1_p = landslide0_1_p;
M_.params(11) = 1/(1+M_.params(6)-M_.params(5));
omegaQA_1_p = M_.params(11);
M_.params(12) = 0.01;
etaQA_1_p = M_.params(12);
M_.params(13) = 0;
iGA_1_p = M_.params(13);
M_.params(14) = 0;
iIAP_1_p = M_.params(14);
omega_1_p = 1/inbsectors_p;
M_.params(21) = 0.5;
omegaM_1_p = M_.params(21);
M_.params(18) = 1;
D_X_1_p = M_.params(18);
M_.params(19) = 1;
P_M_1_p = M_.params(19);
M_.params(20) = 1;
P_D_1_p = M_.params(20);
M_.params(24) = 1.05;
etaI_1_p = M_.params(24);
M_.params(23) = 2;
etaQ_1_p = M_.params(23);
M_.params(21) = 1/M_.params(1);
omegaM_1_p = M_.params(21);
M_.params(22) = 1/M_.params(1);
omegaQ_1_p = M_.params(22);
M_.params(17) = 0.5;
phiQI_1_p = M_.params(17);
M_.params(16) = 0.5;
phiX_1_p = M_.params(16);
M_.params(25) = 0;
tauKF_1_1_p = M_.params(25);
M_.params(26) = 0;
tauNF_1_1_p = M_.params(26);
M_.params(40) = 1;
A_1_1_p = M_.params(40);
M_.params(44) = 0.025;
omegaA_1_1_p = M_.params(44);
M_.params(42) = 1.06;
gY0_1_1_p = M_.params(42);
M_.params(43) = 1.06;
gN0_1_1_p = M_.params(43);
M_.params(45) = 1;
A_N_1_1_p = M_.params(45);
M_.params(46) = 1;
A_K_1_1_p = M_.params(46);
M_.params(33) = 0.5;
phiW_1_1_p = M_.params(33);
M_.params(30) = 1/(M_.params(1)*M_.params(2));
phiN_1_1_p = M_.params(30);
M_.params(32) = M_.params(30);
phiN0_1_1_p = M_.params(32);
M_.params(31) = M_.params(30);
phiNT_1_1_p = M_.params(31);
M_.params(27) = 1/(M_.params(1)*M_.params(2));
phiY_1_1_p = M_.params(27);
M_.params(29) = M_.params(27);
phiY0_1_1_p = M_.params(29);
M_.params(28) = M_.params(27);
phiYT_1_1_p = M_.params(28);
phiX_1_1_p = 1/2;
M_.params(34) = 1;
phiL_1_1_p = M_.params(34);
M_.params(37) = 0.5;
alphaK_1_1_p = M_.params(37);
M_.params(38) = 0.5;
alphaN_1_1_p = M_.params(38);
M_.params(35) = 1/M_.params(2);
omegaQ_1_1_p = M_.params(35);
M_.params(36) = 0.5;
omegaQI_1_1_p = M_.params(36);
M_.params(39) = 0.95;
etaNK_1_1_p = M_.params(39);
M_.params(41) = 1;
deltaKA_1_1_p = M_.params(41);
M_.params(47) = 1/(1+M_.params(8)-M_.params(7));
omegaQA_2_p = M_.params(47);
M_.params(48) = 0.01;
etaQA_2_p = M_.params(48);
M_.params(49) = 0;
iGA_2_p = M_.params(49);
M_.params(50) = 0;
iIAP_2_p = M_.params(50);
omega_2_p = 1/inbsectors_p;
M_.params(57) = 0.5;
omegaM_2_p = M_.params(57);
M_.params(54) = 1;
D_X_2_p = M_.params(54);
M_.params(55) = 1;
P_M_2_p = M_.params(55);
M_.params(56) = 1;
P_D_2_p = M_.params(56);
M_.params(60) = 1.05;
etaI_2_p = M_.params(60);
M_.params(59) = 2;
etaQ_2_p = M_.params(59);
M_.params(57) = 1/M_.params(1);
omegaM_2_p = M_.params(57);
M_.params(58) = 1/M_.params(1);
omegaQ_2_p = M_.params(58);
M_.params(53) = 0.5;
phiQI_2_p = M_.params(53);
M_.params(52) = 0.5;
phiX_2_p = M_.params(52);
M_.params(61) = 0;
tauKF_2_1_p = M_.params(61);
M_.params(62) = 0;
tauNF_2_1_p = M_.params(62);
M_.params(76) = 1;
A_2_1_p = M_.params(76);
M_.params(80) = 0.025;
omegaA_2_1_p = M_.params(80);
M_.params(78) = 1.06;
gY0_2_1_p = M_.params(78);
M_.params(79) = 1.06;
gN0_2_1_p = M_.params(79);
M_.params(81) = 1;
A_N_2_1_p = M_.params(81);
M_.params(82) = 1;
A_K_2_1_p = M_.params(82);
M_.params(69) = 0.5;
phiW_2_1_p = M_.params(69);
M_.params(66) = 1/(M_.params(1)*M_.params(2));
phiN_2_1_p = M_.params(66);
M_.params(68) = M_.params(66);
phiN0_2_1_p = M_.params(68);
M_.params(67) = M_.params(66);
phiNT_2_1_p = M_.params(67);
M_.params(63) = 1/(M_.params(1)*M_.params(2));
phiY_2_1_p = M_.params(63);
M_.params(65) = M_.params(63);
phiY0_2_1_p = M_.params(65);
M_.params(64) = M_.params(63);
phiYT_2_1_p = M_.params(64);
phiX_2_1_p = 1/2;
M_.params(70) = 1;
phiL_2_1_p = M_.params(70);
M_.params(73) = 0.5;
alphaK_2_1_p = M_.params(73);
M_.params(74) = 0.5;
alphaN_2_1_p = M_.params(74);
M_.params(71) = 1/M_.params(2);
omegaQ_2_1_p = M_.params(71);
M_.params(72) = 0.5;
omegaQI_2_1_p = M_.params(72);
M_.params(75) = 0.95;
etaNK_2_1_p = M_.params(75);
M_.params(77) = 1;
deltaKA_2_1_p = M_.params(77);
M_.params(83) = 1/(1+M_.params(10)-M_.params(9));
omegaQA_3_p = M_.params(83);
M_.params(84) = 0.01;
etaQA_3_p = M_.params(84);
M_.params(85) = 0;
iGA_3_p = M_.params(85);
M_.params(86) = 0;
iIAP_3_p = M_.params(86);
omega_3_p = 1/inbsectors_p;
M_.params(93) = 0.5;
omegaM_3_p = M_.params(93);
M_.params(90) = 1;
D_X_3_p = M_.params(90);
M_.params(91) = 1;
P_M_3_p = M_.params(91);
M_.params(92) = 1;
P_D_3_p = M_.params(92);
M_.params(96) = 1.05;
etaI_3_p = M_.params(96);
M_.params(95) = 2;
etaQ_3_p = M_.params(95);
M_.params(93) = 1/M_.params(1);
omegaM_3_p = M_.params(93);
M_.params(94) = 1/M_.params(1);
omegaQ_3_p = M_.params(94);
M_.params(89) = 0.5;
phiQI_3_p = M_.params(89);
M_.params(88) = 0.5;
phiX_3_p = M_.params(88);
M_.params(97) = 0;
tauKF_3_1_p = M_.params(97);
M_.params(98) = 0;
tauNF_3_1_p = M_.params(98);
M_.params(112) = 1;
A_3_1_p = M_.params(112);
M_.params(116) = 0.025;
omegaA_3_1_p = M_.params(116);
M_.params(114) = 1.06;
gY0_3_1_p = M_.params(114);
M_.params(115) = 1.06;
gN0_3_1_p = M_.params(115);
M_.params(117) = 1;
A_N_3_1_p = M_.params(117);
M_.params(118) = 1;
A_K_3_1_p = M_.params(118);
M_.params(105) = 0.5;
phiW_3_1_p = M_.params(105);
M_.params(102) = 1/(M_.params(1)*M_.params(2));
phiN_3_1_p = M_.params(102);
M_.params(104) = M_.params(102);
phiN0_3_1_p = M_.params(104);
M_.params(103) = M_.params(102);
phiNT_3_1_p = M_.params(103);
M_.params(99) = 1/(M_.params(1)*M_.params(2));
phiY_3_1_p = M_.params(99);
M_.params(101) = M_.params(99);
phiY0_3_1_p = M_.params(101);
M_.params(100) = M_.params(99);
phiYT_3_1_p = M_.params(100);
phiX_3_1_p = 1/2;
M_.params(106) = 1;
phiL_3_1_p = M_.params(106);
M_.params(109) = 0.5;
alphaK_3_1_p = M_.params(109);
M_.params(110) = 0.5;
alphaN_3_1_p = M_.params(110);
M_.params(107) = 1/M_.params(2);
omegaQ_3_1_p = M_.params(107);
M_.params(108) = 0.5;
omegaQI_3_1_p = M_.params(108);
M_.params(111) = 0.95;
etaNK_3_1_p = M_.params(111);
M_.params(113) = 1;
deltaKA_3_1_p = M_.params(113);
TempValues = readtable(sWorkbookNameInput, 'Sheet', 'Start','Range','A:C');
[lParams,iaMparams] = ismember(cellstr(M_.param_names), TempValues.Parameter);
M_.params(lParams) = TempValues.Value(iaMparams(iaMparams>0));
TempValues = readtable(sWorkbookNameInput, 'Sheet', 'Structural Parameters','Range','A:C');
[lParams,iaMparams] = ismember(cellstr(M_.param_names), TempValues.Parameter);
M_.params(lParams) = TempValues.Value(iaMparams(iaMparams>0));
DefineAuxiliaryExpressions
sVersion = ['Sectors' num2str(imaxsec_p) 'Regions' num2str(inbregions_p) sSensitivity];
SteadyState_Model
Simulation_Model
if exist('structScenarioResults.mat', 'file')
load('structScenarioResults.mat', 'structScenarioResults')
structScenarioResults.(sVersion).(sScenario).oo_ = oo_;
structScenarioResults.(sVersion).(sScenario).M_ = M_;
structScenarioResults.(sVersion).(sScenario).options_ = options_;    
save('structScenarioResults.mat', 'structScenarioResults', '-append')
else
structScenarioResults.(sVersion).(sScenario).oo_ = oo_;
structScenarioResults.(sVersion).(sScenario).M_ = M_;
structScenarioResults.(sVersion).(sScenario).options_ = options_; 
save('structScenarioResults.mat', 'structScenarioResults')
end


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'DGE_CRED_Model_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DGE_CRED_Model_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DGE_CRED_Model_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DGE_CRED_Model_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DGE_CRED_Model_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DGE_CRED_Model_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DGE_CRED_Model_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
